/*******************************************************************************************
  WELL_TEST_ANALYSIS  (View)

  20150818  cdong   include IHS US data (tis task 1164), adapted code by vrajpoot

 *******************************************************************************************/

--drop view ppdm.well_test_analysis;

 
create or replace force view ppdm.well_test_analysis
(
   uwi,
   source,
   test_type,
   run_num,
   test_num,
   period_type,
   period_obs_no,
   analysis_obs_no,
   active_ind,
   bsw,
   completion_obs_no,
   condensate_gravity,
   condensate_ratio,
   condensate_ratio_ouom,
   condensate_temperature,
   condensate_temperature_ouom,
   effective_date,
   expiry_date,
   fluid_type,
   gas_content,
   gas_gravity,
   gor,
   gor_ouom,
   gwr,
   gwr_ouom,
   h2s_percent,
   lgr,
   lgr_ouom,
   oil_density,
   oil_density_ouom,
   oil_gravity,
   oil_temperature,
   oil_temperature_ouom,
   ppdm_guid,
   remark,
   salinity_type,
   sulphur_percent,
   water_cut,
   water_resistivity,
   water_resistivity_ouom,
   water_salinity,
   water_salinity_ouom,
   water_temperature,
   water_temperature_ouom,
   wor,
   row_changed_by,
   row_changed_date,
   row_created_by,
   row_created_date,
   row_quality,
   province_state
)
as
   select uwi,
          source,
          test_type,
          run_num,
          test_num,
          period_type,
          period_obs_no,
          analysis_obs_no,
          active_ind,
          bsw,
          completion_obs_no,
          condensate_gravity,
          condensate_ratio,
          condensate_ratio_ouom,
          condensate_temperature,
          condensate_temperature_ouom,
          effective_date,
          expiry_date,
          fluid_type,
          gas_content,
          gas_gravity,
          gor,
          gor_ouom,
          gwr,
          gwr_ouom,
          h2s_percent,
          lgr,
          lgr_ouom,
          oil_density,
          oil_density_ouom,
          oil_gravity,
          oil_temperature,
          oil_temperature_ouom,
          ppdm_guid,
          remark,
          salinity_type,
          sulphur_percent,
          water_cut,
          water_resistivity,
          water_resistivity_ouom,
          water_salinity,
          water_salinity_ouom,
          water_temperature,
          water_temperature_ouom,
          wor,
          row_changed_by,
          row_changed_date,
          row_created_by,
          row_created_date,
          row_quality,
          --IHS extension
          NULL    as province_state
     from tlm_well_test_analysis
   union all
   select wta.uwi,
          wta.source,
          wta.test_type,
          wta.run_num,
          wta.test_num,
          wta.period_type,
          wta.period_obs_no,
          wta.analysis_obs_no,
          wta.active_ind,
          wta.bsw,
          wta.completion_obs_no,
          wta.condensate_gravity,
          wta.condensate_ratio,
          wta.condensate_ratio_ouom,
          wta.condensate_temperature,
          wta.condensate_temperature_ouom,
          wta.effective_date,
          wta.expiry_date,
          wta.fluid_type,
          wta.gas_content,
          wta.gas_gravity,
          wta.gor,
          wta.gor_ouom,
          wta.gwr,
          wta.gwr_ouom,
          wta.h2s_percent,
          wta.lgr,
          wta.lgr_ouom,
          wta.oil_density,
          wta.oil_density_ouom,
          wta.oil_gravity,
          wta.oil_temperature,
          wta.oil_temperature_ouom,
          wta.ppdm_guid,
          wta.remark,
          wta.salinity_type,
          wta.sulphur_percent,
          wta.water_cut,
          wta.water_resistivity,
          wta.water_resistivity_ouom,
          wta.water_salinity,
          wta.water_salinity_ouom,
          wta.water_temperature,
          wta.water_temperature_ouom,
          wta.wor,
          wta.row_changed_by,
          wta.row_changed_date,
          wta.row_created_by,
          wta.row_created_date,
          wta.row_quality,
          --IHS extension
          wta.province_state
     from ihs_cdn_well_test_analysis wta
   union all
   select wtau.uwi,
          wtau.source,
          wtau.test_type,
          wtau.run_num,
          wtau.test_num,
          wtau.period_type,
          wtau.period_obs_no,
          wtau.analysis_obs_no,
          wtau.active_ind,
          wtau.bsw,
          wtau.completion_obs_no,
          wtau.condensate_gravity,
          wtau.condensate_ratio,
          wtau.condensate_ratio_ouom,
          wtau.condensate_temperature,
          wtau.condensate_temperature_ouom,
          wtau.effective_date,
          wtau.expiry_date,
          wtau.fluid_type,
          wtau.gas_content,
          wtau.gas_gravity,
          wtau.gor,
          wtau.gor_ouom,
          wtau.gwr,
          wtau.gwr_ouom,
          wtau.h2s_percent,
          wtau.lgr,
          wtau.lgr_ouom,
          wtau.oil_density,
          wtau.oil_density_ouom,
          wtau.oil_gravity,
          wtau.oil_temperature,
          wtau.oil_temperature_ouom,
          wtau.ppdm_guid,
          wtau.remark,
          wtau.salinity_type,
          wtau.sulphur_percent,
          wtau.water_cut,
          wtau.water_resistivity,
          wtau.water_resistivity_ouom,
          wtau.water_salinity,
          wtau.water_salinity_ouom,
          wtau.water_temperature,
          wtau.water_temperature_ouom,
          wtau.wor,
          wtau.row_changed_by,
          wtau.row_changed_date,
          wtau.row_created_by,
          wtau.row_created_date,
          wtau.row_quality,
          --IHS extension
          wtau.province_state
     from ihs_us_well_test_analysis wtau
;


grant select on ppdm.well_test_analysis to ppdm_ro;


--create or replace synonym data_finder.well_test_analysis for ppdm.well_test_analysis;
--create or replace synonym ppdm.wta for ppdm.well_test_analysis;
