DROP MATERIALIZED VIEW WELL_PIDSTG_MV;
CREATE MATERIALIZED VIEW WELL_PIDSTG_MV (UWI,SOURCE,ABANDONMENT_DATE,ACTIVE_IND,ASSIGNED_FIELD,BASE_NODE_ID,BOTTOM_HOLE_LATITUDE,BOTTOM_HOLE_LONGITUDE,CASING_FLANGE_ELEV,CASING_FLANGE_ELEV_OUOM,COMPLETION_DATE,CONFIDENTIAL_DATE,CONFIDENTIAL_DEPTH,CONFIDENTIAL_DEPTH_OUOM,CONFIDENTIAL_TYPE,CONFID_STRAT_NAME_SET_ID,CONFID_STRAT_UNIT_ID,COUNTRY,COUNTY,CURRENT_CLASS,CURRENT_STATUS,CURRENT_STATUS_DATE,DEEPEST_DEPTH,DEEPEST_DEPTH_OUOM,DEPTH_DATUM,DEPTH_DATUM_ELEV,DEPTH_DATUM_ELEV_OUOM,DERRICK_FLOOR_ELEV,DERRICK_FLOOR_ELEV_OUOM,DIFFERENCE_LAT_MSL,DISCOVERY_IND,DISTRICT,DRILL_TD,DRILL_TD_OUOM,EFFECTIVE_DATE,ELEV_REF_DATUM,EXPIRY_DATE,FAULTED_IND,FINAL_DRILL_DATE,FINAL_TD,FINAL_TD_OUOM,GEOGRAPHIC_REGION,GEOLOGIC_PROVINCE,GROUND_ELEV,GROUND_ELEV_OUOM,GROUND_ELEV_TYPE,INITIAL_CLASS,KB_ELEV,KB_ELEV_OUOM,LEASE_NAME,LEASE_NUM,LEGAL_SURVEY_TYPE,LOCATION_TYPE,LOG_TD,LOG_TD_OUOM,MAX_TVD,MAX_TVD_OUOM,NET_PAY,NET_PAY_OUOM,OLDEST_STRAT_AGE,OLDEST_STRAT_NAME_SET_AGE,OLDEST_STRAT_NAME_SET_ID,OLDEST_STRAT_UNIT_ID,OPERATOR,PARENT_RELATIONSHIP_TYPE,PARENT_UWI,PLATFORM_ID,PLATFORM_SF_TYPE,PLOT_NAME,PLOT_SYMBOL,PLUGBACK_DEPTH,PLUGBACK_DEPTH_OUOM,PPDM_GUID,PROFILE_TYPE,PROVINCE_STATE,REGULATORY_AGENCY,REMARK,RIG_ON_SITE_DATE,RIG_RELEASE_DATE,ROTARY_TABLE_ELEV,SOURCE_DOCUMENT,SPUD_DATE,STATUS_TYPE,SUBSEA_ELEV_REF_TYPE,SURFACE_LATITUDE,SURFACE_LONGITUDE,SURFACE_NODE_ID,TAX_CREDIT_CODE,TD_STRAT_AGE,TD_STRAT_NAME_SET_AGE,TD_STRAT_NAME_SET_ID,TD_STRAT_UNIT_ID,WATER_ACOUSTIC_VEL,WATER_ACOUSTIC_VEL_OUOM,WATER_DEPTH,WATER_DEPTH_DATUM,WATER_DEPTH_OUOM,WELL_EVENT_NUM,WELL_GOVERNMENT_ID,WELL_INTERSECT_MD,WELL_NAME,WELL_NUM,WELL_NUMERIC_ID,WHIPSTOCK_DEPTH,WHIPSTOCK_DEPTH_OUOM,IPL_LICENSEE,IPL_OFFSHORE_IND,IPL_PIDSTATUS,IPL_PRSTATUS,IPL_ORSTATUS,IPL_ONPROD_DATE,IPL_ONINJECT_DATE,IPL_CONFIDENTIAL_STRAT_AGE,IPL_POOL,IPL_UWI_SORT,IPL_UWI_DISPLAY,IPL_TD_TVD,IPL_PLUGBACK_TVD,IPL_WHIPSTOCK_TVD,IPL_WATER_TVD,IPL_ALT_SOURCE,IPL_XACTION_CODE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,IPL_BASIN,IPL_BLOCK,IPL_AREA,IPL_TWP,IPL_TRACT,IPL_LOT,IPL_CONC,IPL_UWI_LOCAL,ROW_QUALITY)
TABLESPACE APP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 30/09/2013 9:13:51 AM (QP5 v5.227.12220.39754) */
SELECT UWI,
       PRIMARY_SOURCE AS "SOURCE",
       ABANDONMENT_DATE,
       ACTIVE_IND,
       ASSIGNED_FIELD,
       BASE_NODE_ID,
       BOTTOM_HOLE_LATITUDE,
       BOTTOM_HOLE_LONGITUDE,
       CASING_FLANGE_ELEV,
       CASING_FLANGE_ELEV_OUOM,
       COMPLETION_DATE,
       CONFIDENTIAL_DATE,
       CONFIDENTIAL_DEPTH,
       CONFIDENTIAL_DEPTH_OUOM,
       CONFIDENTIAL_TYPE,
       CONFID_STRAT_NAME_SET_ID,
       CONFID_STRAT_UNIT_ID,
       COUNTRY,
       COUNTY,
       CURRENT_CLASS,
       CURRENT_STATUS,
       CURRENT_STATUS_DATE,
       DEEPEST_DEPTH,
       DEEPEST_DEPTH_OUOM,
       DEPTH_DATUM,
       DEPTH_DATUM_ELEV,
       DEPTH_DATUM_ELEV_OUOM,
       DERRICK_FLOOR_ELEV,
       DERRICK_FLOOR_ELEV_OUOM,
       DIFFERENCE_LAT_MSL,
       DISCOVERY_IND,
       DISTRICT,
       DRILL_TD,
       DRILL_TD_OUOM,
       EFFECTIVE_DATE,
       ELEV_REF_DATUM,
       EXPIRY_DATE,
       FAULTED_IND,
       FINAL_DRILL_DATE,
       FINAL_TD,
       FINAL_TD_OUOM,
       GEOGRAPHIC_REGION,
       GEOLOGIC_PROVINCE,
       GROUND_ELEV,
       GROUND_ELEV_OUOM,
       GROUND_ELEV_TYPE,
       INITIAL_CLASS,
       KB_ELEV,
       KB_ELEV_OUOM,
       LEASE_NAME,
       LEASE_NUM,
       LEGAL_SURVEY_TYPE,
       LOCATION_TYPE,
       LOG_TD,
       LOG_TD_OUOM,
       MAX_TVD,
       MAX_TVD_OUOM,
       NET_PAY,
       NET_PAY_OUOM,
       CAST (OLDEST_STRAT_AGE AS VARCHAR (20)) AS "OLDEST_STRAT_AGE",
       OLDEST_STRAT_NAME_SET_AGE,
       OLDEST_STRAT_NAME_SET_ID,
       OLDEST_STRAT_UNIT_ID,
       OPERATOR,
       PARENT_RELATIONSHIP_TYPE,
       PARENT_UWI,
       PLATFORM_ID,
       PLATFORM_SF_TYPE,
       PLOT_NAME,
       PLOT_SYMBOL,
       PLUGBACK_DEPTH,
       PLUGBACK_DEPTH_OUOM,
       PPDM_GUID,
       PROFILE_TYPE,
       PROVINCE_STATE,
       REGULATORY_AGENCY,
       REMARK,
       RIG_ON_SITE_DATE,
       RIG_RELEASE_DATE,
       ROTARY_TABLE_ELEV,
       SOURCE_DOCUMENT,
       SPUD_DATE,
       STATUS_TYPE,
       SUBSEA_ELEV_REF_TYPE,
       SURFACE_LATITUDE,
       SURFACE_LONGITUDE,
       SURFACE_NODE_ID,
       TAX_CREDIT_CODE,
       TD_STRAT_AGE,
       TD_STRAT_NAME_SET_AGE,
       TD_STRAT_NAME_SET_ID,
       TD_STRAT_UNIT_ID,
       WATER_ACOUSTIC_VEL,
       WATER_ACOUSTIC_VEL_OUOM,
       WATER_DEPTH,
       WATER_DEPTH_DATUM,
       WATER_DEPTH_OUOM,
       WELL_EVENT_NUM,
       WELL_GOVERNMENT_ID,
       WELL_INTERSECT_MD,
       WELL_NAME,
       UWI AS "WELL_NUM",
       WELL_NUMERIC_ID,
       WHIPSTOCK_DEPTH,
       WHIPSTOCK_DEPTH_OUOM,
       x_current_licensee AS "IPL_LICENSEE",
       x_offshore_ind AS "IPL_OFFSHORE_IND",
       CAST ('' AS VARCHAR (12)) AS "IPL_PIDSTATUS",
       x_previous_status AS "IPL_PRSTATUS",
       x_original_status AS "IPL_ORSTATUS",
       x_onprod_date AS "IPL_ONPROD_DATE",
       x_oninject_date AS "IPL_ONINJECT_DATE",
       CAST (confid_strat_age AS VARCHAR (20))
          AS "IPL_CONFIDENTIAL_STRAT_AGE",
       x_pool AS "IPL_POOL",
       -- null as IPL_LAST_UPDATE,
       x_uwi_sort AS "IPL_UWI_SORT",
       x_uwi_display AS "IPL_UWI_DISPLAY",
       x_td_tvd AS "IPL_TD_TVD",
       x_plugback_tvd AS "IPL_PLUGBACK_TVD",
       x_whipstock_tvd AS "IPL_WHIPSTOCK_TVD",
       CAST (NULL AS NUMBER (10, 5)) AS IPL_WATER_TVD,
       CAST ('' AS VARCHAR (12)) AS "IPL_ALT_SOURCE",
       CAST ('' AS VARCHAR (1)) AS "IPL_XACTION_CODE",
       ROW_CHANGED_BY,
       ROW_CHANGED_DATE,
       ROW_CREATED_BY,
       ROW_CREATED_DATE,
       CAST ('' AS VARCHAR (12)) AS "IPL_BASIN",
       CAST ('' AS VARCHAR (12)) AS "IPL_BLOCK",
       CAST ('' AS VARCHAR (12)) AS "IPL_AREA",
       CAST ('' AS VARCHAR (12)) AS "IPL_TWP",
       CAST ('' AS VARCHAR (12)) AS "IPL_TRACT",
       CAST ('' AS VARCHAR (12)) AS "IPL_LOT",
       CAST ('' AS VARCHAR (12)) AS "IPL_CONC",
       UWI AS "IPL_UWI_LOCAL",
       ROW_QUALITY
  FROM WELL@c_talisman_us;


COMMENT ON MATERIALIZED VIEW WELL_PIDSTG_MV IS 'snapshot table for snapshot WIM_LOADER.WELL_VERSIONPIDSTG_MV';

CREATE UNIQUE INDEX WPID_PK ON WELL_PIDSTG_MV
(UWI, SOURCE)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX WPID_WNUM ON WELL_PIDSTG_MV
(WELL_NUM)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX W_PK ON WELL_PIDSTG_MV
(IPL_UWI_LOCAL)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
