DROP MATERIALIZED VIEW WELL_LICENSEPRBSTG_MV;
CREATE MATERIALIZED VIEW WELL_LICENSEPRBSTG_MV (UWI,LICENSE_ID,SOURCE,ACTIVE_IND,AGENT,APPLICATION_ID,AUTHORIZED_STRAT_UNIT_ID,BIDDING_ROUND_NUM,CONTRACTOR,DIRECTION_TO_LOC,DIRECTION_TO_LOC_OUOM,DISTANCE_REF_POINT,DISTANCE_TO_LOC,DISTANCE_TO_LOC_OUOM,DRILL_RIG_NUM,DRILL_SLOT_NO,DRILL_TOOL,EFFECTIVE_DATE,EXCEPTION_GRANTED,EXCEPTION_REQUESTED,EXPIRED_IND,EXPIRY_DATE,FEES_PAID_IND,LICENSEE,LICENSEE_CONTACT_ID,LICENSE_DATE,LICENSE_NUM,NO_OF_WELLS,OFFSHORE_COMPLETION_TYPE,PERMIT_REFERENCE_NUM,PERMIT_REISSUE_DATE,PERMIT_TYPE,PLATFORM_NAME,PPDM_GUID,PROJECTED_DEPTH,PROJECTED_DEPTH_OUOM,PROJECTED_STRAT_UNIT_ID,PROJECTED_TVD,PROJECTED_TVD_OUOM,PROPOSED_SPUD_DATE,PURPOSE,RATE_SCHEDULE_ID,REGULATION,REGULATORY_AGENCY,REGULATORY_CONTACT_ID,REMARK,RIG_CODE,RIG_SUBSTR_HEIGHT,RIG_SUBSTR_HEIGHT_OUOM,RIG_TYPE,SECTION_OF_REGULATION,STRAT_NAME_SET_ID,SURVEYOR,TARGET_OBJECTIVE_FLUID,IPL_PROJECTED_STRAT_AGE,IPL_ALT_SOURCE,IPL_XACTION_CODE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,IPL_WELL_OBJECTIVE,ROW_QUALITY,IPL_UWI_LOCAL)
TABLESPACE APP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 30/09/2013 9:13:48 AM (QP5 v5.227.12220.39754) */
SELECT "WELL_LICENSE"."UWI" "UWI",
       "WELL_LICENSE"."LICENSE_ID" "LICENSE_ID",
       "WELL_LICENSE"."SOURCE" "SOURCE",
       "WELL_LICENSE"."ACTIVE_IND" "ACTIVE_IND",
       "WELL_LICENSE"."AGENT" "AGENT",
       "WELL_LICENSE"."APPLICATION_ID" "APPLICATION_ID",
       "WELL_LICENSE"."AUTHORIZED_STRAT_UNIT_ID" "AUTHORIZED_STRAT_UNIT_ID",
       "WELL_LICENSE"."BIDDING_ROUND_NUM" "BIDDING_ROUND_NUM",
       "WELL_LICENSE"."CONTRACTOR" "CONTRACTOR",
       "WELL_LICENSE"."DIRECTION_TO_LOC" "DIRECTION_TO_LOC",
       "WELL_LICENSE"."DIRECTION_TO_LOC_OUOM" "DIRECTION_TO_LOC_OUOM",
       "WELL_LICENSE"."DISTANCE_REF_POINT" "DISTANCE_REF_POINT",
       "WELL_LICENSE"."DISTANCE_TO_LOC" "DISTANCE_TO_LOC",
       "WELL_LICENSE"."DISTANCE_TO_LOC_OUOM" "DISTANCE_TO_LOC_OUOM",
       "WELL_LICENSE"."DRILL_RIG_NUM" "DRILL_RIG_NUM",
       "WELL_LICENSE"."DRILL_SLOT_NO" "DRILL_SLOT_NO",
       "WELL_LICENSE"."DRILL_TOOL" "DRILL_TOOL",
       "WELL_LICENSE"."EFFECTIVE_DATE" "EFFECTIVE_DATE",
       "WELL_LICENSE"."EXCEPTION_GRANTED" "EXCEPTION_GRANTED",
       "WELL_LICENSE"."EXCEPTION_REQUESTED" "EXCEPTION_REQUESTED",
       "WELL_LICENSE"."EXPIRED_IND" "EXPIRED_IND",
       "WELL_LICENSE"."EXPIRY_DATE" "EXPIRY_DATE",
       "WELL_LICENSE"."FEES_PAID_IND" "FEES_PAID_IND",
       "WELL_LICENSE"."LICENSEE" "LICENSEE",
       "WELL_LICENSE"."LICENSEE_CONTACT_ID" "LICENSEE_CONTACT_ID",
       "WELL_LICENSE"."LICENSE_DATE" "LICENSE_DATE",
       "WELL_LICENSE"."LICENSE_NUM" "LICENSE_NUM",
       "WELL_LICENSE"."NO_OF_WELLS" "NO_OF_WELLS",
       "WELL_LICENSE"."OFFSHORE_COMPLETION_TYPE" "OFFSHORE_COMPLETION_TYPE",
       "WELL_LICENSE"."PERMIT_REFERENCE_NUM" "PERMIT_REFERENCE_NUM",
       "WELL_LICENSE"."PERMIT_REISSUE_DATE" "PERMIT_REISSUE_DATE",
       "WELL_LICENSE"."PERMIT_TYPE" "PERMIT_TYPE",
       "WELL_LICENSE"."PLATFORM_NAME" "PLATFORM_NAME",
       "WELL_LICENSE"."PPDM_GUID" "PPDM_GUID",
       "WELL_LICENSE"."PROJECTED_DEPTH" "PROJECTED_DEPTH",
       "WELL_LICENSE"."PROJECTED_DEPTH_OUOM" "PROJECTED_DEPTH_OUOM",
       "WELL_LICENSE"."PROJECTED_STRAT_UNIT_ID" "PROJECTED_STRAT_UNIT_ID",
       "WELL_LICENSE"."PROJECTED_TVD" "PROJECTED_TVD",
       "WELL_LICENSE"."PROJECTED_TVD_OUOM" "PROJECTED_TVD_OUOM",
       "WELL_LICENSE"."PROPOSED_SPUD_DATE" "PROPOSED_SPUD_DATE",
       "WELL_LICENSE"."PURPOSE" "PURPOSE",
       "WELL_LICENSE"."RATE_SCHEDULE_ID" "RATE_SCHEDULE_ID",
       "WELL_LICENSE"."REGULATION" "REGULATION",
       "WELL_LICENSE"."REGULATORY_AGENCY" "REGULATORY_AGENCY",
       "WELL_LICENSE"."REGULATORY_CONTACT_ID" "REGULATORY_CONTACT_ID",
       "WELL_LICENSE"."REMARK" "REMARK",
       "WELL_LICENSE"."RIG_CODE" "RIG_CODE",
       "WELL_LICENSE"."RIG_SUBSTR_HEIGHT" "RIG_SUBSTR_HEIGHT",
       "WELL_LICENSE"."RIG_SUBSTR_HEIGHT_OUOM" "RIG_SUBSTR_HEIGHT_OUOM",
       "WELL_LICENSE"."RIG_TYPE" "RIG_TYPE",
       "WELL_LICENSE"."SECTION_OF_REGULATION" "SECTION_OF_REGULATION",
       "WELL_LICENSE"."STRAT_NAME_SET_ID" "STRAT_NAME_SET_ID",
       "WELL_LICENSE"."SURVEYOR" "SURVEYOR",
       "WELL_LICENSE"."TARGET_OBJECTIVE_FLUID" "TARGET_OBJECTIVE_FLUID",
       "WELL_LICENSE"."IPL_PROJECTED_STRAT_AGE" "IPL_PROJECTED_STRAT_AGE",
       "WELL_LICENSE"."IPL_ALT_SOURCE" "IPL_ALT_SOURCE",
       "WELL_LICENSE"."IPL_XACTION_CODE" "IPL_XACTION_CODE",
       "WELL_LICENSE"."ROW_CHANGED_BY" "ROW_CHANGED_BY",
       "WELL_LICENSE"."ROW_CHANGED_DATE" "ROW_CHANGED_DATE",
       "WELL_LICENSE"."ROW_CREATED_BY" "ROW_CREATED_BY",
       "WELL_LICENSE"."ROW_CREATED_DATE" "ROW_CREATED_DATE",
       "WELL_LICENSE"."IPL_WELL_OBJECTIVE" "IPL_WELL_OBJECTIVE",
       "WELL_LICENSE"."ROW_QUALITY" "ROW_QUALITY",
       "WELL_LICENSE"."IPL_UWI_LOCAL" "IPL_UWI_LOCAL"
  FROM "S_TLM_PROBE_STG"."WELL_LICENSE"@C_TLM_PROBE.WORLD "WELL_LICENSE";


COMMENT ON MATERIALIZED VIEW WELL_LICENSEPRBSTG_MV IS 'snapshot table for snapshot WIM_LOADER.WELL_LICENSEPRBSTG_MV';

CREATE UNIQUE INDEX WLIC_PK1 ON WELL_LICENSEPRBSTG_MV
(UWI, LICENSE_ID, SOURCE)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX WLPRB_UWI ON WELL_LICENSEPRBSTG_MV
(UWI)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
