 drop materialized view WELL_NODE_VERSIONPIDSTG_MV
 ;
 
  CREATE MATERIALIZED VIEW "WIM_LOADER"."WELL_NODE_VERSIONPIDSTG_MV" ("NODE_ID", "SOURCE", "NODE_OBS_NO", "ACQUISITION_ID", "ACTIVE_IND", "COUNTRY", "COUNTY", "EASTING", "EASTING_OUOM", "EFFECTIVE_DATE", "ELEV", "ELEV_OUOM", "EW_DIRECTION", "EXPIRY_DATE", "GEOG_COORD_SYSTEM_ID_ORIG", "GEOG_COORD_SYSTEM_ID", "LATITUDE", "LEGAL_SURVEY_TYPE", "LOCATION_QUALIFIER", "LOCATION_QUALITY", "LONGITUDE", "MAP_COORD_SYSTEM_ID", "MD", "MD_OUOM", "MONUMENT_ID", "MONUMENT_SF_TYPE", "NODE_POSITION", "NORTHING", "NORTHING_OUOM", "NORTH_TYPE", "NS_DIRECTION", "POLAR_AZIMUTH", "POLAR_OFFSET", "POLAR_OFFSET_OUOM", "PPDM_GUID", "PREFERRED_IND", "PROVINCE_STATE", "REMARK", "REPORTED_TVD", "REPORTED_TVD_OUOM", "VERSION_TYPE", "X_OFFSET", "X_OFFSET_OUOM", "Y_OFFSET", "Y_OFFSET_OUOM", "ROW_CHANGED_BY", "ROW_CHANGED_DATE", "ROW_CREATED_BY", "ROW_CREATED_DATE", "UWI", "ROW_QUALITY")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 0 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT NODE_ID,
       SOURCE,
       NODE_OBS_NO,
       ACQUISITION_ID,
       ACTIVE_IND,
       COUNTRY,
       COUNTY,
       EASTING,
       EASTING_OUOM,
       EFFECTIVE_DATE,
       ELEV,
       ELEV_OUOM,
       EW_DIRECTION,
       EXPIRY_DATE,
	   geog_coord_system_id GEOG_COORD_SYSTEM_ID_ORIG,
	   -- QC# 1475 - this value is now converted using the below function in the stage view.
--       PPDM_ADMIN.TLM_UTIL.GET_COORD_SYSTEM_ID(geog_coord_system_id),
       geog_coord_system_id,
       LATITUDE,
       LEGAL_SURVEY_TYPE,
       LOCATION_QUALIFIER,
       LOCATION_QUALITY,
       LONGITUDE,
       MAP_COORD_SYSTEM_ID,
       MD,
       MD_OUOM,
       MONUMENT_ID,
       MONUMENT_SF_TYPE,
       NODE_POSITION,
       NORTHING,
       NORTHING_OUOM,
       NORTH_TYPE,
       NS_DIRECTION,
       POLAR_AZIMUTH,
       POLAR_OFFSET,
       POLAR_OFFSET_OUOM,
       PPDM_GUID,
       PREFERRED_IND,
       PROVINCE_STATE,
       REMARK,
       REPORTED_TVD,
       REPORTED_TVD_OUOM,
       VERSION_TYPE,
       X_OFFSET,
       X_OFFSET_OUOM,
       Y_OFFSET,
       Y_OFFSET_OUOM,
       -- '' as "IPL_XACTION_CODE",
       ROW_CHANGED_BY,
       ROW_CHANGED_DATE,
       ROW_CREATED_BY,
       ROW_CREATED_DATE,
       UWI,
       ROW_QUALITY
  FROM WELL_NODE_VERSION@c_talisman_us;

  CREATE UNIQUE INDEX "WIM_LOADER"."WNV_PK" ON "WIM_LOADER"."WELL_NODE_VERSIONPIDSTG_MV" ("NODE_ID", "SOURCE", "NODE_OBS_NO", "GEOG_COORD_SYSTEM_ID_ORIG", "LOCATION_QUALIFIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;
  
  CREATE INDEX "WIM_LOADER"."WNV_PID_IDX1" ON "WIM_LOADER"."WELL_NODE_VERSIONPIDSTG_MV" ("UWI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;

   COMMENT ON MATERIALIZED VIEW "WIM_LOADER"."WELL_NODE_VERSIONPIDSTG_MV"  IS 'snapshot table for snapshot WIM_LOADER.WELL_NODE_VERSIONPIDSTG_MV';
