DROP MATERIALIZED VIEW WELL_STATUSPRBSTG_MV;
CREATE MATERIALIZED VIEW WELL_STATUSPRBSTG_MV (UWI,SOURCE,STATUS_ID,ACTIVE_IND,EFFECTIVE_DATE,EXPIRY_DATE,PPDM_GUID,REMARK,STATUS,STATUS_DATE,STATUS_DEPTH,STATUS_DEPTH_OUOM,IPL_XACTION_CODE,STATUS_TYPE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_QUALITY,IPL_UWI_LOCAL)
TABLESPACE APP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 30/09/2013 9:13:52 AM (QP5 v5.227.12220.39754) */
SELECT "WELL_STATUS"."UWI" "UWI",
       "WELL_STATUS"."SOURCE" "SOURCE",
       "WELL_STATUS"."STATUS_ID" "STATUS_ID",
       "WELL_STATUS"."ACTIVE_IND" "ACTIVE_IND",
       "WELL_STATUS"."EFFECTIVE_DATE" "EFFECTIVE_DATE",
       "WELL_STATUS"."EXPIRY_DATE" "EXPIRY_DATE",
       "WELL_STATUS"."PPDM_GUID" "PPDM_GUID",
       "WELL_STATUS"."REMARK" "REMARK",
       "WELL_STATUS"."STATUS" "STATUS",
       "WELL_STATUS"."STATUS_DATE" "STATUS_DATE",
       "WELL_STATUS"."STATUS_DEPTH" "STATUS_DEPTH",
       "WELL_STATUS"."STATUS_DEPTH_OUOM" "STATUS_DEPTH_OUOM",
       "WELL_STATUS"."IPL_XACTION_CODE" "IPL_XACTION_CODE",
       "WELL_STATUS"."STATUS_TYPE" "STATUS_TYPE",
       "WELL_STATUS"."ROW_CHANGED_BY" "ROW_CHANGED_BY",
       "WELL_STATUS"."ROW_CHANGED_DATE" "ROW_CHANGED_DATE",
       "WELL_STATUS"."ROW_CREATED_BY" "ROW_CREATED_BY",
       "WELL_STATUS"."ROW_CREATED_DATE" "ROW_CREATED_DATE",
       "WELL_STATUS"."ROW_QUALITY" "ROW_QUALITY",
       "WELL_STATUS"."IPL_UWI_LOCAL" "IPL_UWI_LOCAL"
  FROM "S_TLM_PROBE_STG"."WELL_STATUS"@C_TLM_PROBE.WORLD "WELL_STATUS";


COMMENT ON MATERIALIZED VIEW WELL_STATUSPRBSTG_MV IS 'snapshot table for snapshot WIM_LOADER.WELL_STATUSPRBSTG_MV';

CREATE INDEX WSPPRB_UWI ON WELL_STATUSPRBSTG_MV
(UWI)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX WST_PK1 ON WELL_STATUSPRBSTG_MV
(UWI, SOURCE, STATUS_ID)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
