DROP MATERIALIZED VIEW WELL_STATUSIPL_STG_MV;
CREATE MATERIALIZED VIEW WELL_STATUSIPL_STG_MV (UWI,SOURCE,STATUS_ID,ACTIVE_IND,EFFECTIVE_DATE,EXPIRY_DATE,PPDM_GUID,REMARK,STATUS,STATUS_DATE,STATUS_DEPTH,STATUS_DEPTH_OUOM,STATUS_TYPE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_QUALITY,PROVINCE_STATE)
TABLESPACE APP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 30/09/2013 9:13:51 AM (QP5 v5.227.12220.39754) */
SELECT *
  FROM ( (SELECT * FROM well_status@c_talisman_ihsdata));


COMMENT ON MATERIALIZED VIEW WELL_STATUSIPL_STG_MV IS 'snapshot table for snapshot WIM_LOADER.WELL_STATUSIPL_STG_MV';

CREATE INDEX WSIPL_UWI ON WELL_STATUSIPL_STG_MV
(UWI)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
