'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''_Default class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class _Default

  '''<summary>
  '''LblSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblSearch As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMessage1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMessage1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMessage2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMessage2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''DataGrid1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DataGrid1 As Global.ComponentArt.Web.UI.DataGrid

  '''<summary>
  '''dlgFind control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dlgFind As Global.ComponentArt.Web.UI.Dialog

  '''<summary>
  '''ddlAliasType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlAliasType As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txtValue control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtValue As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cbckFind control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cbckFind As Global.ComponentArt.Web.UI.CallBack

  '''<summary>
  '''cbckRemove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cbckRemove As Global.ComponentArt.Web.UI.CallBack

  '''<summary>
  '''lblFindError control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblFindError As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnAddRows control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddRows As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnRemoveRows control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnRemoveRows As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnAddVersion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddVersion As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnEditVersion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnEditVersion As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnInactivateVersion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnInactivateVersion As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnDeleteVersion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnDeleteVersion As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''btnMoveVersion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnMoveVersion As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''AddVersionsAllowed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AddVersionsAllowed As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''DeleteVersionsAllowed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DeleteVersionsAllowed As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''EditVersionsAllowed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents EditVersionsAllowed As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''InactivateVersionsAllowed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents InactivateVersionsAllowed As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''MoveVersionsAllowed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MoveVersionsAllowed As Global.System.Web.UI.WebControls.HiddenField
End Class
