DROP VIEW PPDM.IHS_CDN_PDEN_PROD_ZONE;

/* Formatted on 4/2/2013 7:35:45 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_CDN_PDEN_PROD_ZONE
(
   PDEN_ID,
   PDEN_TYPE,
   SOURCE,
   STRAT_UNIT_ID,
   TOP_DEPTH,
   BASE_DEPTH,
   COMPLETION_TOP,
   COMPLETION_BASE,
   PROVINCE_STATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_QUALITY,
   STRAT_UNIT_AGE,
   BASE_STRAT_AGE,
   COMPLETION_DATE,
   PLUGBACK_DATE,
   STRAT_NAME_SET_ID
)
AS
   SELECT 
         WV.UWI AS "PDEN_ID",
          PPZ."PDEN_TYPE",
          WV.SOURCE AS "SOURCE",
          PPZ."STRAT_UNIT_ID",
          PPZ."TOP_DEPTH",
          PPZ."BASE_DEPTH",
          PPZ."COMPLETION_TOP",
          PPZ."COMPLETION_BASE",
          PPZ."PROVINCE_STATE",
          PPZ."ROW_CREATED_BY",
          PPZ."ROW_CREATED_DATE",
          PPZ."ROW_CHANGED_BY",
          PPZ."ROW_CHANGED_DATE",
          PPZ."ROW_QUALITY",
          PPZ."STRAT_UNIT_AGE",
          PPZ."BASE_STRAT_AGE",
          PPZ."COMPLETION_DATE",
          PPZ."PLUGBACK_DATE",
          PPZ."STRAT_NAME_SET_ID"
     FROM PDEN_PROD_ZONE@C_TALISMAN_IHSDATA PPZ, WELL_VERSION WV
    WHERE     WV.IPL_UWI_LOCAL = PPZ.PDEN_ID
          AND PPZ.PDEN_TYPE = 'PDEN_WELL'
          AND WV.SOURCE = '300IPL'
          AND WV.ACTIVE_IND = 'Y';


GRANT SELECT ON PPDM.IHS_CDN_PDEN_PROD_ZONE TO PPDM_RO;
