DROP VIEW PPDM.IHS_PID_PDEN_PROD_ZONE;

/* Formatted on 2/4/2013 2:51:42 PM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_PID_PDEN_PROD_ZONE
(
    ENTITY,
    PDEN_TYPE,
    SOURCE,
    ACTIVE_IND,
    PROD_ZONE,
    top_depth,
    BASE_DEPTH,
    PROVINCE_STATE,          
    row_CHANGED_DATE, --pi_rec_upd_date,
    ROW_CREATED_BY, --PI_USER_ID,
    ROW_CREATED_dATE, --PI_ROW_ADD_DATE,
    COMPLETION_DATE   
)
AS
   SELECT WV.uwi as "PDEN_ID",
          P.ENTITY_TYPE AS "PDEN_TYPE",
          '450PID' AS SOURCE,
          'Y' AS ACTIVE_IND,
          PpW.PROD_ZONE,
          PpW.top_depth,
          PpW.BASE_DEPTH,
          RPS.SHORT_NAME AS PROVINCE_STATE,          
          p.pi_rec_upd_date,
          P.PI_USER_ID,
          P.PI_ROW_ADD_DATE,
          P.COMPLETION_DATE
     FROM PDEN@C_TALISMAN_PID_STG_IHSDATAQ P
        --, PI_PROD_WELL@C_TALISMAN_PID_STG_IHSDATAQ PpW
        , PI_Pden_WELL@C_TALISMAN_PID_STG_IHSDATAQ PpW
        , WELL_VERSION WV
        , R_GEOLOGIC_PROV@C_TALISMAN_PID_STG_IHSDATAQ RGP
        , R_PRODUCT_TYPE@C_TALISMAN_PID_STG_IHSDATAQ RPT
        , R_PROVINCE_STATE@C_TALISMAN_PID_STG_IHSDATAQ RPS
   WHERE  P.ENTITY = PPW.ENTITY
      AND PPW.well_identifier = WV.WELL_NUM
      AND P.GEOLOGIC_PROVINCE = RGP.GEOLOGIC_PROVINCE
      AND P.PI_PRIMARY_PRODUCT = RPT.PRODUCT_TYPE
      AND P.PROVINCE_STATE = RPS.PROVINCE_STATE
      AND WV.SOURCE = '450PID'
      AND WV.ACTIVE_IND = 'Y'; 


GRANT SELECT ON PPDM.IHS_PID_PDEN_PROD_ZONE TO PPDM_RO;
