DROP TABLE PPDM.PDEN CASCADE CONSTRAINTS;

DROP VIEW PPDM.PDEN;

/* Formatted on 4/2/2013 7:31:29 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.PDEN
(
   PDEN_ID,
   PDEN_TYPE,
   SOURCE,
   ACTIVE_IND,
   COUNTRY,
   CURRENT_OPERATOR,
   CURRENT_PROD_STR_NAME,
   CURRENT_STATUS_DATE,
   CURRENT_WELL_STR_NUMBER,
   DISTRICT,
   EFFECTIVE_DATE,
   ENHANCED_RECOVERY_TYPE,
   EXPIRY_DATE,
   FIELD_ID,
   GEOGRAPHIC_REGION,
   GEOLOGIC_PROVINCE,
   LAST_INJECTION_DATE,
   LAST_PRODUCTION_DATE,
   LAST_REPORTED_DATE,
   LOCATION_DESC,
   LOCATION_DESC_TYPE,
   ON_INJECTION_DATE,
   ON_PRODUCTION_DATE,
   PDEN_NAME,
   PDEN_SHORT_NAME,
   PDEN_STATUS,
   PLOT_NAME,
   PLOT_SYMBOL,
   POOL_ID,
   PPDM_GUID,
   PRIMARY_PRODUCT,
   PRODUCTION_METHOD,
   PROPRIETARY_IND,
   PROVINCE_STATE,
   REMARK,
   STATE_OR_FEDERAL_WATERS,
   STRAT_NAME_SET_ID,
   STRAT_UNIT_ID,
   STRING_SERIAL_NUMBER,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   X_TOP_DEPTH,
   X_BASE_DEPTH,
   X_UNIT_ID,
   X_ALLOW_TYPE,
   X_BLOCK_ID,
   X_PSU_SURPLUS_IND,
   X_PROJECT_ID,
   X_PROD_FREQ,
   X_PROD_SPACING_UNIT,
   X_UNIT_OIL_INTEREST,
   X_UNIT_GAS_INTEREST,
   X_SPECIAL_PSU_SURPLUS,
   X_SPECIAL_PENALTY_RELIEF,
   X_PENALTY_RELIEF,
   X_SET_GOR_DATE,
   X_SET_GOR,
   X_PEND_S4_IND,
   X_FACILITY_ID,
   X_CONTROL_WELL_IND,
   X_OIL_DENSITY,
   X_OFF_TARGET,
   X_DISP_INJ_APPROVAL,
   X_DISP_INJ_APPROVAL_NUMBER,
   X_WELLHEAD_PRESS,
   X_BATTERY_ID,
   X_COMMINGLED,
   TOP_STRAT_AGE,
   BASE_STRAT_AGE,
   X_ONPROD_OIL,
   X_ONPROD_GAS,
   X_ONPROD_WATER,
   FACILITY_TYPE
)
AS
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "ACTIVE_IND",
          "COUNTRY",
          "CURRENT_OPERATOR",
          "CURRENT_PROD_STR_NAME",
          "CURRENT_STATUS_DATE",
          "CURRENT_WELL_STR_NUMBER",
          "DISTRICT",
          "EFFECTIVE_DATE",
          "ENHANCED_RECOVERY_TYPE",
          "EXPIRY_DATE",
          "FIELD_ID",
          "GEOGRAPHIC_REGION",
          "GEOLOGIC_PROVINCE",
          "LAST_INJECTION_DATE",
          "LAST_PRODUCTION_DATE",
          "LAST_REPORTED_DATE",
          "LOCATION_DESC",
          "LOCATION_DESC_TYPE",
          "ON_INJECTION_DATE",
          "ON_PRODUCTION_DATE",
          "PDEN_NAME",
          "PDEN_SHORT_NAME",
          "PDEN_STATUS",
          "PLOT_NAME",
          "PLOT_SYMBOL",
          "POOL_ID",
          "PPDM_GUID",
          "PRIMARY_PRODUCT",
          "PRODUCTION_METHOD",
          "PROPRIETARY_IND",
          "PROVINCE_STATE",
          "REMARK",
          "STATE_OR_FEDERAL_WATERS",
          "STRAT_NAME_SET_ID",
          "STRAT_UNIT_ID",
          "STRING_SERIAL_NUMBER",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS Extensions
          NULL AS "X_TOP_DEPTH",
          NULL AS "X_BASE_DEPTH",
          NULL AS "X_UNIT_ID",
          NULL AS "X_ALLOW_TYPE",
          NULL AS "X_BLOCK_ID",
          NULL AS "X_PSU_SURPLUS_IND",
          NULL AS "X_PROJECT_ID",
          NULL AS "X_PROD_FREQ",
          NULL AS "X_PROD_SPACING_UNIT",
          NULL AS "X_UNIT_OIL_INTEREST",
          NULL AS "X_UNIT_GAS_INTEREST",
          NULL AS "X_SPECIAL_PSU_SURPLUS",
          NULL AS "X_SPECIAL_PENALTY_RELIEF",
          NULL AS "X_PENALTY_RELIEF",
          NULL AS "X_SET_GOR_DATE",
          NULL AS "X_SET_GOR",
          NULL AS "X_PEND_S4_IND",
          NULL AS "X_FACILITY_ID",
          NULL AS "X_CONTROL_WELL_IND",
          NULL AS "X_OIL_DENSITY",
          NULL AS "X_OFF_TARGET",
          NULL AS "X_DISP_INJ_APPROVAL",
          NULL AS "X_DISP_INJ_APPROVAL_NUMBER",
          NULL AS "X_WELLHEAD_PRESS",
          NULL AS "X_BATTERY_ID",
          NULL AS "X_COMMINGLED",
          NULL AS "TOP_STRAT_AGE",
          NULL AS "BASE_STRAT_AGE",
          NULL AS "X_ONPROD_OIL",
          NULL AS "X_ONPROD_GAS",
          NULL AS "X_ONPROD_WATER",
          NULL AS "FACILITY_TYPE"
     FROM TLM_PDEN
   UNION ALL
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "ACTIVE_IND",
          "COUNTRY",
          "CURRENT_OPERATOR",
          "CURRENT_PROD_STR_NAME",
          "CURRENT_STATUS_DATE",
          "CURRENT_WELL_STR_NUMBER",
          "DISTRICT",
          "EFFECTIVE_DATE",
          "ENHANCED_RECOVERY_TYPE",
          "EXPIRY_DATE",
          "FIELD_ID",
          "GEOGRAPHIC_REGION",
          "GEOLOGIC_PROVINCE",
          "LAST_INJECTION_DATE",
          "LAST_PRODUCTION_DATE",
          "LAST_REPORTED_DATE",
          "LOCATION_DESC",
          "LOCATION_DESC_TYPE",
          "ON_INJECTION_DATE",
          "ON_PRODUCTION_DATE",
          "PDEN_NAME",
          "PDEN_SHORT_NAME",
          "PDEN_STATUS",
          "PLOT_NAME",
          "PLOT_SYMBOL",
          "POOL_ID",
          "PPDM_GUID",
          "PRIMARY_PRODUCT",
          "PRODUCTION_METHOD",
          "PROPRIETARY_IND",
          "PROVINCE_STATE",
          "REMARK",
          "STATE_OR_FEDERAL_WATERS",
          "STRAT_NAME_SET_ID",
          "STRAT_UNIT_ID",
          "STRING_SERIAL_NUMBER",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS Extensions
          "X_TOP_DEPTH",
          "X_BASE_DEPTH",
          "X_UNIT_ID",
          "X_ALLOW_TYPE",
          "X_BLOCK_ID",
          "X_PSU_SURPLUS_IND",
          "X_PROJECT_ID",
          "X_PROD_FREQ",
          "X_PROD_SPACING_UNIT",
          "X_UNIT_OIL_INTEREST",
          "X_UNIT_GAS_INTEREST",
          "X_SPECIAL_PSU_SURPLUS",
          "X_SPECIAL_PENALTY_RELIEF",
          "X_PENALTY_RELIEF",
          "X_SET_GOR_DATE",
          "X_SET_GOR",
          "X_PEND_S4_IND",
          "X_FACILITY_ID",
          "X_CONTROL_WELL_IND",
          "X_OIL_DENSITY",
          "X_OFF_TARGET",
          "X_DISP_INJ_APPROVAL",
          "X_DISP_INJ_APPROVAL_NUMBER",
          "X_WELLHEAD_PRESS",
          "X_BATTERY_ID",
          "X_COMMINGLED",
          "TOP_STRAT_AGE",
          "BASE_STRAT_AGE",
          "X_ONPROD_OIL",
          "X_ONPROD_GAS",
          "X_ONPROD_WATER",
          "FACILITY_TYPE"
     FROM IHS_CDN_PDEN
   UNION ALL
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "ACTIVE_IND",
          "COUNTRY",
          "CURRENT_OPERATOR",
          "CURRENT_PROD_STR_NAME",
          "CURRENT_STATUS_DATE",
          "CURRENT_WELL_STR_NUMBER",
          "DISTRICT",
          "EFFECTIVE_DATE",
          "ENHANCED_RECOVERY_TYPE",
          "EXPIRY_DATE",
          "FIELD_ID",
          "GEOGRAPHIC_REGION",
          "GEOLOGIC_PROVINCE",
          "LAST_INJECTION_DATE",
          "LAST_PRODUCTION_DATE",
          "LAST_REPORTED_DATE",
          "LOCATION_DESC",
          "LOCATION_DESC_TYPE",
          "ON_INJECTION_DATE",
          "ON_PRODUCTION_DATE",
          "PDEN_NAME",
          "PDEN_SHORT_NAME",
          "PDEN_STATUS",
          "PLOT_NAME",
          "PLOT_SYMBOL",
          "POOL_ID",
          "PPDM_GUID",
          "PRIMARY_PRODUCT",
          "PRODUCTION_METHOD",
          "PROPRIETARY_IND",
          "PROVINCE_STATE",
          "REMARK",
          "STATE_OR_FEDERAL_WATERS",
          "STRAT_NAME_SET_ID",
          "STRAT_UNIT_ID",
          "STRING_SERIAL_NUMBER",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS Extensions
          "X_TOP_DEPTH",
          "X_BASE_DEPTH",
          "X_UNIT_ID",
          "X_ALLOW_TYPE",
          "X_BLOCK_ID",
          "X_PSU_SURPLUS_IND",
          "X_PROJECT_ID",
          "X_PROD_FREQ",
          "X_PROD_SPACING_UNIT",
          "X_UNIT_OIL_INTEREST",
          "X_UNIT_GAS_INTEREST",
          "X_SPECIAL_PSU_SURPLUS",
          "X_SPECIAL_PENALTY_RELIEF",
          "X_PENALTY_RELIEF",
          "X_SET_GOR_DATE",
          "X_SET_GOR",
          "X_PEND_S4_IND",
          "X_FACILITY_ID",
          "X_CONTROL_WELL_IND",
          "X_OIL_DENSITY",
          "X_OFF_TARGET",
          "X_DISP_INJ_APPROVAL",
          "X_DISP_INJ_APPROVAL_NUMBER",
          "X_WELLHEAD_PRESS",
          "X_BATTERY_ID",
          "X_COMMINGLED",
          "TOP_STRAT_AGE",
          "BASE_STRAT_AGE",
          "X_ONPROD_OIL",
          "X_ONPROD_GAS",
          "X_ONPROD_WATER",
          "FACILITY_TYPE"
     FROM IHS_US_PDEN;


DROP SYNONYM DATA_FINDER.PDEN;

CREATE OR REPLACE SYNONYM DATA_FINDER.PDEN FOR PPDM.PDEN;


DROP SYNONYM EDIOS_ADMIN.PDEN;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.PDEN FOR PPDM.PDEN;


DROP SYNONYM PPDM.PD;

CREATE OR REPLACE SYNONYM PPDM.PD FOR PPDM.PDEN;


DROP SYNONYM PPDM_ADMIN.PDEN;

CREATE OR REPLACE SYNONYM PPDM_ADMIN.PDEN FOR PPDM.PDEN;

DROP SYNONYM WIM.PDEN;
CREATE OR REPLACE SYNONYM WIM.PDEN FOR PPDM.PDEN;


GRANT SELECT ON PPDM.PDEN TO EDIOS_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.PDEN TO PPDM_ADMIN;
GRANT SELECT ON PPDM.PDEN TO PPDM_RO;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.PDEN TO PPDM_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.PDEN TO WIM;
