DROP VIEW PPDM.PDEN_PROD_ZONE;

/* Formatted on 4/2/2013 7:31:03 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.PDEN_PROD_ZONE
(
   PDEN_ID,
   PDEN_TYPE,
   SOURCE,
   STRAT_UNIT_ID,
   TOP_DEPTH,
   BASE_DEPTH,
   COMPLETION_TOP,
   COMPLETION_BASE,
   PROVINCE_STATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_QUALITY,
   STRAT_UNIT_AGE,
   BASE_STRAT_AGE,
   COMPLETION_DATE,
   PLUGBACK_DATE,
   STRAT_NAME_SET_ID
)
AS
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "STRAT_UNIT_ID",
          "TOP_DEPTH",
          "BASE_DEPTH",
          "COMPLETION_TOP",
          "COMPLETION_BASE",
          "PROVINCE_STATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_QUALITY",
          "STRAT_UNIT_AGE",
          "BASE_STRAT_AGE",
          "COMPLETION_DATE",
          "PLUGBACK_DATE",
          "STRAT_NAME_SET_ID"
     FROM TLM_PDEN_PROD_ZONE
   UNION ALL
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "STRAT_UNIT_ID",
          "TOP_DEPTH",
          "BASE_DEPTH",
          "COMPLETION_TOP",
          "COMPLETION_BASE",
          "PROVINCE_STATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_QUALITY",
          "STRAT_UNIT_AGE",
          "BASE_STRAT_AGE",
          "COMPLETION_DATE",
          "PLUGBACK_DATE",
          "STRAT_NAME_SET_ID"
     FROM IHS_CDN_PDEN_PROD_ZONE
   UNION ALL
   SELECT "PDEN_ID",
          "PDEN_TYPE",
          "SOURCE",
          "STRAT_UNIT_ID",
          "TOP_DEPTH",
          "BASE_DEPTH",
          "COMPLETION_TOP",
          "COMPLETION_BASE",
          "PROVINCE_STATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_QUALITY",
          "STRAT_UNIT_AGE",
          "BASE_STRAT_AGE",
          "COMPLETION_DATE",
          "PLUGBACK_DATE",
          "STRAT_NAME_SET_ID"
     FROM IHS_US_PDEN_PROD_ZONE;


GRANT SELECT ON PPDM.PDEN_PROD_ZONE TO PPDM_RO;


DROP SYNONYM DATA_FINDER.PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM DATA_FINDER.PDEN_PROD_ZONE FOR PPDM.PDEN_PROD_ZONE;


DROP SYNONYM EDIOS_ADMIN.PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.PDEN_PROD_ZONE FOR PPDM.PDEN_PROD_ZONE;


DROP SYNONYM PPDM.PDENP_PROD_ZONE;
CREATE OR REPLACE SYNONYM PPDM.PDENP_PROD_ZONE FOR PPDM.PDEN_PROD_ZONE;


