--New table
ALTER TABLE PPDM.TLM_PDEN_PROD_ZONE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PPDM.TLM_PDEN_PROD_ZONE CASCADE CONSTRAINTS;

CREATE TABLE PPDM.TLM_PDEN_PROD_ZONE
(
  PDEN_ID                  VARCHAR2(40 BYTE)    NOT NULL,
  PDEN_TYPE                VARCHAR2(24 BYTE)    NOT NULL,
  SOURCE                   VARCHAR2(20 BYTE)    NOT NULL,
  STRAT_UNIT_ID            VARCHAR2(20 BYTE)    NOT NULL,
  TOP_DEPTH                NUMBER(9,2),
  BASE_DEPTH               NUMBER(9,2),
  COMPLETION_TOP           NUMBER(9,2),
  COMPLETION_BASE          NUMBER(9,2),
  PROVINCE_STATE           VARCHAR2(20 BYTE)          NOT NULL,
  ROW_CREATED_BY           VARCHAR2(30 BYTE),
  ROW_CREATED_DATE         DATE,
  ROW_CHANGED_BY           VARCHAR2(30 BYTE),
  ROW_CHANGED_DATE         DATE,
  ROW_QUALITY              VARCHAR2(20 BYTE),
  STRAT_UNIT_AGE           NUMBER(12),
  BASE_STRAT_AGE           NUMBER(12),
  COMPLETION_DATE          DATE,
  PLUGBACK_DATE            DATE,
  STRAT_NAME_SET_ID        VARCHAR2(20 BYTE) 
)
TABLESPACE PPDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             80K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PPDM.TLM_PDEN_PROD_ZONE_PK ON PPDM.TLM_PDEN_PROD_ZONE
(PDEN_ID, PDEN_TYPE, SOURCE, STRAT_UNIT_ID)
LOGGING
TABLESPACE PPDM_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64k
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PPDM.TLM_PDEN_PROD_ZONE ADD (
  CONSTRAINT TLM_PDEN_PROD_ZONE_PK
  PRIMARY KEY
  (PDEN_ID, PDEN_TYPE, SOURCE, STRAT_UNIT_ID)
  USING INDEX PPDM.TLM_PDEN_PROD_ZONE_PK
  ENABLE VALIDATE);


GRANT INSERT, SELECT ON PPDM.TLM_PDEN_PROD_ZONE TO DATMANGEO_ADMIN;
GRANT SELECT ON PPDM.TLM_PDEN_PROD_ZONE TO EDIOS_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_PDEN_PROD_ZONE TO PPDM_ADMIN;
GRANT SELECT ON PPDM.TLM_PDEN_PROD_ZONE TO PPDM_RO;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_PDEN_PROD_ZONE TO PPDM_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_PDEN_PROD_ZONE TO WIM;


DROP SYNONYM PPDM_ADMIN.TLM_PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM PPDM_ADMIN.TLM_PDEN_PROD_ZONE FOR PPDM.TLM_PDEN_PROD_ZONE;


DROP SYNONYM WIM.TLM_PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM WIM.TLM_PDEN_PROD_ZONE FOR PPDM.TLM_PDEN_PROD_ZONE;

DROP SYNONYM DATA_FINDER.TLM_PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_PDEN_PROD_ZONE FOR PPDM.TLM_PDEN_PROD_ZONE;

DROP SYNONYM EDIOS_ADMIN.TLM_PDEN_PROD_ZONE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_PDEN_PROD_ZONE FOR PPDM.TLM_PDEN_PROD_ZONE;
