'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''WellVersion class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class WellVersion

    '''<summary>
    '''lblWellVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMndtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMndtry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabStrip1 As Global.ComponentArt.Web.UI.TabStrip

    '''<summary>
    '''MultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiPage1 As Global.ComponentArt.Web.UI.MultiPage

    '''<summary>
    '''PageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageView1 As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''pnlSourceGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSourceGroup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSourceMndtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSourceMndtry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSource As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlIdentityGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIdentityGroup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTLMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTLMID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTLMIDval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTLMIDval As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUWIMndtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUWIMndtry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUWI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUWI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUWI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUWI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCountryMndtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountryMndtry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCountry As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWellNameMndtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellNameMndtry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWellName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWellName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWellName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlotName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlotName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlotName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlotName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOnOffshoreInd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnOffshoreInd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOnOffShoreInd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnOffShoreInd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlOnOffShoreInd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlOnOffShoreInd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWellProfileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellProfileType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlWellProfileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWellProfileType As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlWellProfileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlWellProfileType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCurrentStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlCurrentStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOperator As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlOperator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLicensee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicensee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlLicensee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLicensee As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlLicensee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlLicensee As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlElevationGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlElevationGroup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGroundElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroundElev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGroundElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroundElev As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGroundElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroundElevUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlGroundElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGroundElevUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlGroundElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlGroundElevUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDerrickFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDerrickFloor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDerrickFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDerrickFloor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDerrickFloorUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDerrickFloorUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlDerrickFloorUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDerrickFloorUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlDerrickFloorUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlDerrickFloorUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKBElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKBElev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtKBElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKBElev As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKBElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKBElevUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlKBElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlKBElevUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlKBElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlKBElevUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRotaryTableElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRotaryTableElev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRotaryTableMndtryUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRotaryTableMndtryUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRotaryTableElev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRotaryTableElev As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRotaryTableElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRotaryTableElevUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRotaryTableElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRotaryTableElevUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlRotaryTableElevUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlRotaryTableElevUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWaterDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaterDepth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWaterDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaterDepth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWaterDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaterDepthUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlWaterDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWaterDepthUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlWaterDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlWaterDepthUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCasingFlange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCasingFlange As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCasingFlange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCasingFlange As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCasingFlangeUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCasingFlangeUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCasingFlangeUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCasingFlangeUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlCasingFlangeUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlCasingFlangeUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalDepth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotalDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalDepth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalDepthUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTotalDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTotalDepthUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlTotalDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlTotalDepthUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLicenseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenseNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLicenseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLicenseNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLicenseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenseDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLicenseDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenseDateFormat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLicenseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLicenseDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRigReleaseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRigReleaseDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRigReleaseDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRigReleaseDateFormat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRigReleaseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRigReleaseDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpudDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpudDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpudDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpudDateFormat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSpudDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpudDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFinalDrillDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalDrillDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalDrillDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalDrillDateFormat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFinalDrillDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinalDrillDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlBasin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBasin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBasin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBasin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBasin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBasin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlock As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblProvState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProvState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProvState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProvState As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlProvState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlProvState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCounty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCounty As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLeaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeaseName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLeaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLeaseName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAssignedField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignedField As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAssignedField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignedField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPool As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPool As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAddLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddLocation As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''DataGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataGrid1 As Global.ComponentArt.Web.UI.DataGrid

    '''<summary>
    '''PageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageView2 As Global.ComponentArt.Web.UI.PageView

    '''<summary>
    '''pnlSourceGroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSourceGroup2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSource2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSource2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSource2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveInd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveInd2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveInd2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveInd2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlIdentityGroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIdentityGroup2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTLMID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTLMID2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTLMID2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTLMID2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUWI2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUWI2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUWI2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUWI2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCountry2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountry2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCountry2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountry2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWellName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWellName2val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWellName2val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOSA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOldestStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldestStratAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOldestStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOldestStratAge As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlOldestStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlOldestStratAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlTDSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTDSA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTDStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTDStratAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTDStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTDStratAge As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlTDStratAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlTDStratAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlPlugbackDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlugbackDepth As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPlugbackDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlugbackDepth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlugbackDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlugbackDepth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlugbackDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlugbackDepthUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPlugbackDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlugbackDepthUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlPlugbackDepthUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlPlugbackDepthUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlPlugbackTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlugbackTVD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPlugbackTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlugbackTVD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlugbackTVDMntryUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlugbackTVDMntryUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlugbackTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlugbackTVD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlugbackTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlugbackTVDUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPlugbackTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlugbackTVDUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlPlugbackTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlPlugbackTVDUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMaxTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaxTVD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMaxTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxTVD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMaxTVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxTVD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMaxTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxTVDUnits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMaxTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaxTVDUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtddlMaxTVDUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtddlMaxTVDUnits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEditVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditVersion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVersion As Global.System.Web.UI.WebControls.Button
End Class
