ALTER TABLE PPDM.TLM_WELL_CORE_ANALYSIS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PPDM.TLM_WELL_CORE_ANALYSIS CASCADE CONSTRAINTS;

CREATE TABLE PPDM.TLM_WELL_CORE_ANALYSIS
(
  UWI                    VARCHAR2(20 BYTE)      NOT NULL,
  SOURCE                 VARCHAR2(20 BYTE)      NOT NULL,
  CORE_ID                VARCHAR2(20 BYTE)      NOT NULL,
  ANALYSIS_OBS_NO        NUMBER(8)              NOT NULL,
  ACTIVE_IND             VARCHAR2(1 BYTE),
  ANALYSIS_DATE          DATE,
  ANALYZING_COMPANY      VARCHAR2(20 BYTE),
  ANALYZING_COMPANY_LOC  VARCHAR2(32 BYTE),
  ANALYZING_FILE_NUM     VARCHAR2(15 BYTE),
  CORE_ANALYST_NAME      VARCHAR2(60 BYTE),
  EFFECTIVE_DATE         DATE,
  EXPIRY_DATE            DATE,
  PPDM_GUID              VARCHAR2(38 BYTE),
  PRIMARY_SAMPLE_TYPE    VARCHAR2(20 BYTE),
  REMARK                 VARCHAR2(2000 BYTE),
  SAMPLE_DIAMETER        NUMBER(8,3),
  SAMPLE_DIAMETER_OUOM   VARCHAR2(20 BYTE),
  SAMPLE_LENGTH          NUMBER(6,3),
  SAMPLE_LENGTH_OUOM     VARCHAR2(20 BYTE),
  SAMPLE_SHAPE           VARCHAR2(20 BYTE),
  SECOND_SAMPLE_TYPE     VARCHAR2(20 BYTE),
  ROW_CHANGED_BY         VARCHAR2(30 BYTE),
  ROW_CHANGED_DATE       DATE,
  ROW_CREATED_BY         VARCHAR2(30 BYTE),
  ROW_CREATED_DATE       DATE,
  ROW_QUALITY            VARCHAR2(20 BYTE)
)
TABLESPACE PPDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             80K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PPDM.TLM_WELL_CORE_ANALYSIS IS 'WELL CORE ANALYSIS: The Well Core Analysis table describes the type of sample analytical data collected. Information contained in this table contains information such as sample shape, sample length, sample diameter, and analyst performing   the analysis etc.      ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.UWI IS 'UNIQUE WELL IDENTIFIER: A unique name, code or number designated as the primary key for this row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SOURCE IS 'SOURCE: The individual, company, state, or government agency designated as the source of information for this row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.CORE_ID IS 'CORE ID:  Unique identifier for a well core';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ANALYSIS_OBS_NO IS 'ANALYSIS OBSERVATION NUMBER: Number for each unique analysis observation.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ACTIVE_IND IS 'ACTIVE INDICATOR:  A Y/N flag indicating whether this row of data is currently active or valid.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ANALYSIS_DATE IS 'ANALYSIS DATE: Date the core analysis was performed on the sample.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ANALYZING_COMPANY IS 'ANALYZING COMPANY:  the company that performs the analysis on the well core. ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ANALYZING_COMPANY_LOC IS 'ANALYZING COMPANY LOCATION: Abbreviation of city or town name of the core analyzing laboratory.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ANALYZING_FILE_NUM IS 'ANALYZING FILE NUMBER: File number (report number) containing the core analysis data. The file number is typically supplied by the laboratory.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.CORE_ANALYST_NAME IS 'CORE ANALYST NAME: Code indicating the name of the individual performing the analysis or interpretations.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.EFFECTIVE_DATE IS 'EFFECTIVE DATE:  The date that the data in this row first came into effect.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.EXPIRY_DATE IS 'EXPIRY DATE:  The date that the data in this row was no longer active or in effect.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.PPDM_GUID IS 'PPDM GUID:  This value may be used to provide a global unique identifier for this row of data.  If used, optional PPDM NOT NULL constraints should be created.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.PRIMARY_SAMPLE_TYPE IS 'CORE SAMPLE: The unique identifier for the reference table.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.REMARK IS 'REMARK: Narrative remarks about this row of data.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SAMPLE_DIAMETER IS 'SAMPLE DIAMETER: Diameter of the core sample.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SAMPLE_DIAMETER_OUOM IS 'SAMPLE DIAMETER OUOM: Sample diameter original unit of measure.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SAMPLE_LENGTH IS 'SAMPLE LENGTH: Measured length of the core sample.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SAMPLE_LENGTH_OUOM IS 'SAMPLE LENGTH OUOM: Sample length original unit of measure.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SAMPLE_SHAPE IS 'SAMPLE SHAPE:  The shape of the sample. ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.SECOND_SAMPLE_TYPE IS 'CORE SAMPLE: The unique identifier for the reference table.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ROW_CHANGED_BY IS 'ROW CHANGED BY: Application login id of the user who last changed the row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ROW_CHANGED_DATE IS 'ROW CHANGED DATE: System date of the last time the row was changed.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ROW_CREATED_BY IS 'ROW CREATED BY:  System user who created this row of data.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ROW_CREATED_DATE IS 'ROW CREATED DATE: Date that the row was created on.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANALYSIS.ROW_QUALITY IS 'PPDM ROW QUALILTY:  A set of values indicating the quality of data in this row, usually with reference to the method or procedures used to load the data, although other types of quality reference are permitted.';



CREATE INDEX PPDM.TWCRA_BA_IDX ON PPDM.TLM_WELL_CORE_ANALYSIS
(ANALYZING_COMPANY)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_OUOM_IDX ON PPDM.TLM_WELL_CORE_ANALYSIS
(SAMPLE_DIAMETER_OUOM)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_OUOM_IDX1 ON PPDM.TLM_WELL_CORE_ANALYSIS
(SAMPLE_LENGTH_OUOM)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PPDM.TWCRA_PK ON PPDM.TLM_WELL_CORE_ANALYSIS
(UWI, SOURCE, CORE_ID, ANALYSIS_OBS_NO)
LOGGING
TABLESPACE PPDM_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_R_CST2_IDX ON PPDM.TLM_WELL_CORE_ANALYSIS
(PRIMARY_SAMPLE_TYPE)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_R_CST2_IDX2 ON PPDM.TLM_WELL_CORE_ANALYSIS
(SECOND_SAMPLE_TYPE)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_R_SS_IDX ON PPDM.TLM_WELL_CORE_ANALYSIS
(SAMPLE_SHAPE)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRA_WCR_IDX ON PPDM.TLM_WELL_CORE_ANALYSIS
(UWI, SOURCE, CORE_ID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;

DROP SYNONYM PPDM_ADMIN.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM PPDM_ADMIN.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;

DROP SYNONYM DATA_FINDER.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;


ALTER TABLE PPDM.TLM_WELL_CORE_ANALYSIS ADD (
  CONSTRAINT TWCRA_PK
  PRIMARY KEY
  (UWI, SOURCE, CORE_ID, ANALYSIS_OBS_NO)
  USING INDEX PPDM.TWCRA_PK
  ENABLE VALIDATE);

ALTER TABLE PPDM.TLM_WELL_CORE_ANALYSIS ADD (
  CONSTRAINT TWCRA_BA_FK 
  FOREIGN KEY (ANALYZING_COMPANY) 
  REFERENCES PPDM.BUSINESS_ASSOCIATE (BUSINESS_ASSOCIATE)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_OUOM_FK 
  FOREIGN KEY (SAMPLE_DIAMETER_OUOM) 
  REFERENCES PPDM.PPDM_UNIT_OF_MEASURE (UOM_ID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_OUOM_FK1 
  FOREIGN KEY (SAMPLE_LENGTH_OUOM) 
  REFERENCES PPDM.PPDM_UNIT_OF_MEASURE (UOM_ID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_R_CST2_FK 
  FOREIGN KEY (PRIMARY_SAMPLE_TYPE) 
  REFERENCES PPDM.R_CORE_SAMPLE_TYPE (CORE_SAMPLE)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_R_CST2_FK2 
  FOREIGN KEY (SECOND_SAMPLE_TYPE) 
  REFERENCES PPDM.R_CORE_SAMPLE_TYPE (CORE_SAMPLE)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_R_SS_FK 
  FOREIGN KEY (SAMPLE_SHAPE) 
  REFERENCES PPDM.R_SAMPLE_SHAPE (SAMPLE_SHAPE_TYPE)
  ENABLE VALIDATE,
  CONSTRAINT TWCRA_WCR_FK 
  FOREIGN KEY (UWI, SOURCE, CORE_ID) 
  REFERENCES PPDM.TLM_WELL_CORE (UWI,SOURCE,CORE_ID)
  ENABLE VALIDATE);

GRANT INSERT, SELECT ON PPDM.TLM_WELL_CORE_ANALYSIS TO DATMANGEO_ADMIN;

GRANT SELECT ON PPDM.TLM_WELL_CORE_ANALYSIS TO EDIOS_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_WELL_CORE_ANALYSIS TO PPDM_ADMIN;

GRANT SELECT ON PPDM.TLM_WELL_CORE_ANALYSIS TO PPDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_WELL_CORE_ANALYSIS TO PPDM_RW;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_WELL_CORE_ANALYSIS TO WIM;
