ALTER TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD CASCADE CONSTRAINTS;

CREATE TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD
(
  UWI                      VARCHAR2(20 BYTE)    NOT NULL,
  SOURCE                   VARCHAR2(20 BYTE)    NOT NULL,
  CORE_ID                  VARCHAR2(20 BYTE)    NOT NULL,
  ANALYSIS_OBS_NO          NUMBER(8)            NOT NULL,
  ACTIVE_IND               VARCHAR2(1 BYTE),
  CORE_SOLVENT             VARCHAR2(20 BYTE),
  CUTTING_FLUID            VARCHAR2(20 BYTE),
  DENSITY_ANALYSIS         VARCHAR2(50 BYTE),
  DRYING_METHOD            VARCHAR2(50 BYTE),
  DRYING_TEMPERATURE       NUMBER(5,2),
  DRYING_TEMPERATURE_OUOM  VARCHAR2(20 BYTE),
  DRYING_TIME              NUMBER(7,2),
  DRYING_TIME_OUOM         VARCHAR2(20 BYTE),
  EFFECTIVE_DATE           DATE,
  EXPIRY_DATE              DATE,
  EXTRACT_METHOD           VARCHAR2(50 BYTE),
  EXTRACT_TIME             NUMBER(7,2),
  EXTRACT_TIME_OUOM        VARCHAR2(20 BYTE),
  FLUID_SAT_ANALYSIS       VARCHAR2(50 BYTE),
  PERMEABILITY_ANALYSIS    VARCHAR2(50 BYTE),
  POROSITY_ANALYSIS        VARCHAR2(50 BYTE),
  PPDM_GUID                VARCHAR2(38 BYTE),
  REMARK                   VARCHAR2(2000 BYTE),
  ROW_CHANGED_BY           VARCHAR2(30 BYTE),
  ROW_CHANGED_DATE         DATE,
  ROW_CREATED_BY           VARCHAR2(30 BYTE),
  ROW_CREATED_DATE         DATE,
  ROW_QUALITY              VARCHAR2(20 BYTE)
)
TABLESPACE PPDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             80K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD IS 'WELL CORE ANALYSIS METHOD: The Well Core Analysis Method table contains information pertaining to the methods used during a core analysis. For example,SOLVENT stores a code representing the type of solvent (such as toluene) used for distil  lation extraction. DRYING records how the core was dried after the extraction process has been completed,such as a high temperature oven or low temperature controlled humidity.      ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.UWI IS 'UNIQUE WELL IDENTIFIER: A unique name, code or number designated as the primary key for this row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.SOURCE IS 'SOURCE: The individual, company, state, or government agency designated as the source of information for this row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.CORE_ID IS 'CORE ID:  Unique identifier for a well core';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ANALYSIS_OBS_NO IS 'ANALYSIS OBSERVATION NUMBER: Number for each unique analysis observation.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ACTIVE_IND IS 'ACTIVE INDICATOR:  A Y/N flag indicating whether this row of data is currently active or valid.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.CORE_SOLVENT IS 'ID: The unique identifier for the reference table.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.CUTTING_FLUID IS 'ID: The unique identifier for the reference table.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DENSITY_ANALYSIS IS 'DENSITY ANALYSIS: Describes the method used for density measurements (e.g., Boyle"s Law) .    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DRYING_METHOD IS 'DRYING METHOD: Narrative text on the method used to dry the core plug after the cleaning process, such as high temperature oven.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DRYING_TEMPERATURE IS 'DRY TEMPERATURE: Temperature maintained during the drying process.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DRYING_TEMPERATURE_OUOM IS 'DRYING TEMPERATURE OUOM: Drying temperature original unit of measure.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DRYING_TIME IS 'CORE DRYING TIME: Time required to dry the core after the extraction process has been completed.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.DRYING_TIME_OUOM IS 'DRYING TIME OUOM: Core dry time original unit of measure.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.EFFECTIVE_DATE IS 'EFFECTIVE DATE:  The date that the data in this row first came into effect.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.EXPIRY_DATE IS 'EXPIRY DATE:  The date that the data in this row was no longer active or in effect.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.EXTRACT_METHOD IS 'EXTRACT METHOD: Descriptive comments associated with the method used to extract any residual fluids present in the core plug  (e.g., vacuum distillation)    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.EXTRACT_TIME IS 'EXTRACT TIME: Time required to extract any residual fluids present in the core.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.EXTRACT_TIME_OUOM IS 'EXTRACTION TIME OUOM: Core extraction time original unit of measure.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.FLUID_SAT_ANALYSIS IS 'FLUID SATURATION ANALYSIS: Comments on the method used for fluid saturation (e.g., solvent extraction, vacuum distillation, retort, etc.).    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.PERMEABILITY_ANALYSIS IS 'PERMEABILITY ANALYSIS: Any comment about the method used to measure permeability (e.g., Darcy"s Law, empirical technique, etc.).    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.POROSITY_ANALYSIS IS 'POROSITY ANALYSIS: Describes the method used to measure porosity (e.g., Boyle"s Law, Helium, Retort fluids, etc.).    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.PPDM_GUID IS 'PPDM GUID:  This value may be used to provide a global unique identifier for this row of data.  If used, optional PPDM NOT NULL constraints should be created.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.REMARK IS 'REMARK: Narrative remarks about this row of data.    ';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ROW_CHANGED_BY IS 'ROW CHANGED BY: Application login id of the user who last changed the row.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ROW_CHANGED_DATE IS 'ROW CHANGED DATE: System date of the last time the row was changed.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ROW_CREATED_BY IS 'ROW CREATED BY:  System user who created this row of data.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ROW_CREATED_DATE IS 'ROW CREATED DATE: Date that the row was created on.';

COMMENT ON COLUMN PPDM.TLM_WELL_CORE_ANAL_METHOD.ROW_QUALITY IS 'PPDM ROW QUALILTY:  A set of values indicating the quality of data in this row, usually with reference to the method or procedures used to load the data, although other types of quality reference are permitted.';



CREATE INDEX PPDM.TWCRAM_OUOM_IDX ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(DRYING_TEMPERATURE_OUOM)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRAM_OUOM_IDX1 ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(DRYING_TIME_OUOM)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRAM_OUOM_IDX2 ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(EXTRACT_TIME_OUOM)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PPDM.TWCRAM_PK ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(UWI, SOURCE, CORE_ID, ANALYSIS_OBS_NO)
LOGGING
TABLESPACE PPDM_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRAM_R_CF_IDX ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(CUTTING_FLUID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TWCRAM_R_CS1_IDX ON PPDM.TLM_WELL_CORE_ANAL_METHOD
(CORE_SOLVENT)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM DATA_FINDER.TLM_WELL_CORE_ANAL_METHOD;

CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_ANAL_METHOD FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;


DROP SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANAL_METHOD;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANAL_METHOD FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;


DROP SYNONYM PPDM.WCRAM;

CREATE OR REPLACE SYNONYM PPDM.WCRAM FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;




ALTER TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD ADD (
  CONSTRAINT TWCRAM_PK
  PRIMARY KEY
  (UWI, SOURCE, CORE_ID, ANALYSIS_OBS_NO)
  USING INDEX PPDM.TWCRAM_PK
  ENABLE VALIDATE);

ALTER TABLE PPDM.TLM_WELL_CORE_ANAL_METHOD ADD (
  CONSTRAINT TWCRAM_OUOM_FK 
  FOREIGN KEY (DRYING_TEMPERATURE_OUOM) 
  REFERENCES PPDM.PPDM_UNIT_OF_MEASURE (UOM_ID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRAM_OUOM_FK1 
  FOREIGN KEY (DRYING_TIME_OUOM) 
  REFERENCES PPDM.PPDM_UNIT_OF_MEASURE (UOM_ID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRAM_OUOM_FK2 
  FOREIGN KEY (EXTRACT_TIME_OUOM) 
  REFERENCES PPDM.PPDM_UNIT_OF_MEASURE (UOM_ID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRAM_R_CF_FK 
  FOREIGN KEY (CUTTING_FLUID) 
  REFERENCES PPDM.R_CUTTING_FLUID (CUTTING_FLUID)
  ENABLE VALIDATE,
  CONSTRAINT TWCRAM_R_CS1_FK 
  FOREIGN KEY (CORE_SOLVENT) 
  REFERENCES PPDM.R_CORE_SOLVENT (CORE_SOLVENT)
  ENABLE VALIDATE,
  CONSTRAINT TWCRAM_WCRA_FK 
  FOREIGN KEY (UWI, SOURCE, CORE_ID, ANALYSIS_OBS_NO) 
  REFERENCES PPDM.WELL_CORE_ANALYSIS (UWI,SOURCE,CORE_ID,ANALYSIS_OBS_NO)
  ENABLE VALIDATE);

GRANT INSERT, SELECT ON PPDM.TLM_WELL_CORE_ANAL_METHOD TO DATMANGEO_ADMIN;

GRANT SELECT ON PPDM.TLM_WELL_CORE_ANAL_METHOD TO EDIOS_ADMIN;

GRANT SELECT ON PPDM.TLM_WELL_CORE_ANAL_METHOD TO PPDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_WELL_CORE_ANAL_METHOD TO PPDM_RW;

