ALTER TABLE BLACK_LIST_WELLS
 DROP PRIMARY KEY CASCADE;

DROP TABLE BLACK_LIST_WELLS CASCADE CONSTRAINTS;

CREATE TABLE BLACK_LIST_WELLS
(
  TLM_ID            VARCHAR2(20 BYTE)           NOT NULL,
  SOURCE            VARCHAR2(20 BYTE)           NOT NULL,
  REMARK            VARCHAR2(2000 BYTE),
  REQUESTED_BY      VARCHAR2(30 BYTE),
  TIMEOUT_DATE      DATE,
  ROW_CHANGED_DATE  DATE,
  ROW_CHANGED_BY    VARCHAR2(30 BYTE),
  ROW_CREATED_DATE  DATE,
  ROW_CREATED_BY    VARCHAR2(30 BYTE)
)
TABLESPACE APP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BLW_PK ON BLACK_LIST_WELLS
(TLM_ID, SOURCE)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BLW_SOURCE ON BLACK_LIST_WELLS
(SOURCE)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BLW_TLM_ID ON BLACK_LIST_WELLS
(TLM_ID)
LOGGING
TABLESPACE APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BLACK_LIST_WELLS ADD (
  CONSTRAINT BLW_PK
  PRIMARY KEY
  (TLM_ID, SOURCE)
  USING INDEX BLW_PK
  ENABLE VALIDATE);

ALTER TABLE BLACK_LIST_WELLS ADD (
  CONSTRAINT BLACK_LIST_WELLS_R01 
  FOREIGN KEY (TLM_ID, SOURCE) 
  REFERENCES PPDM.WELL_VERSION (UWI,SOURCE)
  ENABLE VALIDATE);
