
  CREATE TABLE "WIM_LOADER"."PROBE_WELL_STATUS_STG" 
   (	"UWI" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(20 BYTE), 
	"STATUS_ID" VARCHAR2(20 BYTE), 
	"ACTIVE_IND" VARCHAR2(1 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"PPDM_GUID" VARCHAR2(38 BYTE), 
	"REMARK" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"STATUS_DATE" DATE, 
	"STATUS_DEPTH" NUMBER(10,5), 
	"STATUS_DEPTH_CUOM" VARCHAR2(2 BYTE), 
	"STATUS_DEPTH_OUOM" VARCHAR2(20 BYTE), 
	"IPL_XACTION_CODE" VARCHAR2(1 BYTE), 
	"STATUS_TYPE" VARCHAR2(20 BYTE), 
	"ROW_CHANGED_BY" VARCHAR2(30 BYTE), 
	"ROW_CHANGED_DATE" DATE, 
	"ROW_CREATED_BY" VARCHAR2(30 BYTE), 
	"ROW_CREATED_DATE" DATE, 
	"ROW_QUALITY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;
