
  CREATE TABLE "WIM_LOADER"."PROBE_WELL_CHANGES" 
   (	"WELL_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APP_DATA" ;