
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_STRAT_WELL_INTERP_AGE FOR PPDM.TLM_STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.STRAT_WELL_SECTION FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.STRAT_WELL_INTERP_AGE FOR PPDM.STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.STRAT_UNIT FOR PPDM.STRAT_UNIT;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.STRAT_NAME_SET FOR PPDM.STRAT_NAME_SET;

CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_STRAT_WELL_INTERP_AGE FOR PPDM.TLM_STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM DATA_FINDER.STRAT_WELL_SECTION FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM DATA_FINDER.STRAT_WELL_INTERP_AGE FOR PPDM.STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM DATA_FINDER.STRAT_UNIT FOR PPDM.STRAT_UNIT;
CREATE OR REPLACE SYNONYM DATA_FINDER.STRAT_NAME_SET FOR PPDM.STRAT_NAME_SET;


CREATE OR REPLACE SYNONYM EDIOS_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;

CREATE OR REPLACE SYNONYM GEOWIZ.STRAT_WELL_SECTION FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM GEOWIZ.STRAT_WELL_INTERP_AGE FOR PPDM.STRAT_WELL_INTERP_AGE;

CREATE OR REPLACE SYNONYM GEOWIZ_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM GEOFRAME_APPL.STRAT_WELL_SECTION FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM GEOFRAME_APPL.STRAT_WELL_INTERP_AGE FOR PPDM.STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM GEOFRAME_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM GEOFRAME.STRAT_WELL_SECTION FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM GEOFRAME.STRAT_WELL_INTERP_AGE FOR PPDM.STRAT_WELL_INTERP_AGE;


CREATE OR REPLACE SYNONYM PPDM.STWS FOR PPDM.STRAT_WELL_SECTION;
CREATE OR REPLACE SYNONYM PPDM.STWIA FOR PPDM.STRAT_WELL_INTERP_AGE;
CREATE OR REPLACE SYNONYM PPDM.STU FOR PPDM.STRAT_UNIT;
CREATE OR REPLACE SYNONYM STNS FOR STRAT_NAME_SET;

CREATE OR REPLACE SYNONYM ADD_WELL_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM BO_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;
CREATE OR REPLACE SYNONYM DM_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM IWIM_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;

CREATE OR REPLACE SYNONYM SDRS_IR_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM SPATIAL_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;


CREATE OR REPLACE SYNONYM WORK_LOG_APPL.STRAT_UNIT FOR PPDM.STRAT_UNIT;
