ALTER TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE CASCADE CONSTRAINTS;

CREATE TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE
(
  UWI                         VARCHAR2(20 BYTE) NOT NULL,
  STRAT_NAME_SET_ID           VARCHAR2(20 BYTE) NOT NULL,
  STRAT_UNIT_ID               VARCHAR2(20 BYTE) NOT NULL,
  INTERP_ID                   VARCHAR2(20 BYTE) NOT NULL,
  AGE_SOURCE                  VARCHAR2(20 BYTE) NOT NULL,
  AGE_ID                      NUMBER(12) NOT NULL,
  ACTIVE_IND                  VARCHAR2(1 BYTE),
  SOURCE                      VARCHAR2(20 BYTE),
  AVERAGE_AGE                 NUMBER(15,5),
  AVERAGE_AGE_ERROR_MINUS     NUMBER(15,5),
  AVERAGE_AGE_ERROR_PLUS      NUMBER(15,5),
  AVERAGE_REL_STRAT_NAME_SET  VARCHAR2(20 BYTE),
  AVERAGE_REL_STRAT_UNIT_ID   VARCHAR2(20 BYTE),
  EFFECTIVE_DATE              DATE,
  EXPIRY_DATE                 DATE,
  LOWER_MAX_AGE               NUMBER(15,5),
  LOWER_MAX_AGE_ERROR_MINUS   NUMBER(15,5),
  LOWER_MAX_AGE_ERROR_PLUS    NUMBER(15,5),
  LOWER_MIN_AGE               NUMBER(15,5),
  LOWER_MIN_AGE_ERROR_MINUS   NUMBER(15,5),
  LOWER_MIN_AGE_ERROR_PLUS    NUMBER(15,5),
  LOWER_REL_STRAT_NAME_SET    VARCHAR2(20 BYTE),
  LOWER_REL_STRAT_UNIT_ID     VARCHAR2(20 BYTE),
  POST_QUALIFIER              VARCHAR2(20 BYTE),
  PPDM_GUID                   VARCHAR2(38 BYTE),
  PREFERRED_IND               VARCHAR2(1 BYTE),
  PRE_QUALIFIER               VARCHAR2(20 BYTE),
  REMARK                      VARCHAR2(2000 BYTE),
  SOURCE_DOCUMENT             VARCHAR2(20 BYTE),
  STRAT_AGE_METHOD            VARCHAR2(20 BYTE),
  UPPER_MAX_AGE               NUMBER(15,5),
  UPPER_MAX_AGE_ERROR_MINUS   NUMBER(15,5),
  UPPER_MAX_AGE_ERROR_PLUS    NUMBER(15,5),
  UPPER_MIN_AGE               NUMBER(15,5),
  UPPER_MIN_AGE_ERROR_MINUS   NUMBER(15,5),
  UPPER_MIN_AGE_ERROR_PLUS    NUMBER(15,5),
  UPPER_REL_STRAT_NAME_SET    VARCHAR2(20 BYTE),
  UPPER_REL_STRAT_UNIT_ID     VARCHAR2(20 BYTE),
  ROW_CHANGED_BY              VARCHAR2(30 BYTE),
  ROW_CHANGED_DATE            DATE,
  ROW_CREATED_BY              VARCHAR2(30 BYTE),
  ROW_CREATED_DATE            DATE,
  ROW_QUALITY                 VARCHAR2(20 BYTE)
)
TABLESPACE PPDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             80K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE IS 'STRATIGRAPHIC WELL INTERPRETATION AGE:  the age of a stratigraphic  unit as it occurs in the context of a well interpretation.  Ages may  be expressed in ordinal or chronological terms.       ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UWI IS 'UNIQUE WELL IDENTIFIER: A unique name, code or number designated as the primary key for this row.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.STRAT_NAME_SET_ID IS 'STRAT NAME SET IDENTIFIER:  Unique identifier for the stratigraphic name set.  A stratigraphic name set is an unordered  collection of   stratigraphic units, that may be in use for a Lexicon,  a geographic area, a project, a company etc.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.STRAT_UNIT_ID IS 'STRATIGRAPHIC UNIT IDENTIFIER:  unique identifier for the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.INTERP_ID IS 'INTERPRETATOPM IDENTIFIER:  a unique value added to enable a single strat unit to be identified more than once as part of a stratigraphic column.  Multiple occurances may occur for many reasons, including folding, faulting or a non-vertical interpretation of the strat column. ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AGE_SOURCE IS 'SOURCE: The individual, company, state, or government agency designated as the source of information for this row.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AGE_ID IS 'AGE IDENTIFIER:  Unique identifier for the age in this interpretation.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ACTIVE_IND IS 'ACTIVE INDICATOR:  A Y/N flag indicating whether this row of data is currently active or valid.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AVERAGE_AGE IS 'AVERAGE AGE:  The average age, in years, of the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AVERAGE_AGE_ERROR_MINUS IS 'AVERAGE AGE ERROR MINUS:  The negative error in the average age reference';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AVERAGE_AGE_ERROR_PLUS IS 'AVERAGE AGE ERROR PLUS:  The positive error in the average age reference.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AVERAGE_REL_STRAT_NAME_SET IS 'STRAT NAME SET IDENTIFIER:  Unique identifier for the stratigraphic name set.  A stratigraphic name set is an unordered  collection of   stratigraphic units, that may be in use for a Lexicon,  a geographic area, a project, a company etc.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.AVERAGE_REL_STRAT_UNIT_ID IS 'AVERAGE RELATIVE STRATIGRAPHIC UNIT ID:  unique identifier for the stratigraphic unit that represents the relative (chronologic) age of this stratigraphic unit. ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.EFFECTIVE_DATE IS 'EFFECTIVE DATE:  The date that the data in this row first came into effect.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.EXPIRY_DATE IS 'EXPIRY DATE:  The date that the data in this row was no longer active or in effect.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MAX_AGE IS 'LOWER MAXIMUM AGE:  The maximum lower age, in years, of the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MAX_AGE_ERROR_MINUS IS 'AGE ERROR MINUS:  the negative error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MAX_AGE_ERROR_PLUS IS 'AGE ERROR PLUS:  the positive error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MIN_AGE IS 'LOWER MINIMUM AGE:  The minimum lower age, in years, of the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MIN_AGE_ERROR_MINUS IS 'AGE ERROR MINUS:  the negative error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_MIN_AGE_ERROR_PLUS IS 'AGE ERROR PLUS:  the positive error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_REL_STRAT_NAME_SET IS 'STRAT NAME SET IDENTIFIER:  Unique identifier for the stratigraphic name set.  A stratigraphic name set is an unordered  collection of   stratigraphic units, that may be in use for a Lexicon,  a geographic area, a project, a company etc.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.LOWER_REL_STRAT_UNIT_ID IS 'LOWER RELATIVE STRAT UNIT ID:  The name of the chronostratigraphic age that is the equivalent of the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.POST_QUALIFIER IS 'POST QUALIFIER:  qualifier for the end of the row of data.     ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.PPDM_GUID IS 'PPDM GUID:  This value may be used to provide a global unique identifier for this row of data.  If used, optional PPDM NOT NULL constraints should be created.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.PREFERRED_IND IS 'PREFERRED INDICATOR:  a yes / no flag that indicates whether this data is a preferred version that should be used for reports and maps';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.PRE_QUALIFIER IS 'PRE QUALIFIER:  qualifying statement for the beginning of the row of  data.     ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.REMARK IS 'REMARK:  narrative comments about the age.    ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.SOURCE_DOCUMENT IS 'SOURCE DOCUMENT: A list of documents that are used  as the source for supplying data.  Source documents may include government and regulatory forms, operator reports or scout tickets, publications, news letters, books or jounals. ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.STRAT_AGE_METHOD IS 'REFERENCE STRATIGRAPHIC AGE METHOD:  The method used to determine the age of this stratigraphic unit, such as  radiometric, fossil analysis etc. ';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MAX_AGE IS 'UPPER MAXIMUM AGE:  The maximum upper age, in years, of the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MAX_AGE_ERROR_MINUS IS 'AGE ERROR MINUS:  the negative error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MAX_AGE_ERROR_PLUS IS 'AGE ERROR PLUS:  the positive error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MIN_AGE IS 'UPPER MINIMUM AGE:  The minimum upper age, in years, of the stratigraphic unit.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MIN_AGE_ERROR_MINUS IS 'AGE ERROR MINUS:  the negative error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_MIN_AGE_ERROR_PLUS IS 'AGE ERROR PLUS:  the positive error in the age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_REL_STRAT_NAME_SET IS 'STRAT NAME SET IDENTIFIER:  Unique identifier for the stratigraphic name set.  A stratigraphic name set is an unordered  collection of   stratigraphic units, that may be in use for a Lexicon,  a geographic area, a project, a company etc.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.UPPER_REL_STRAT_UNIT_ID IS 'UPPER RELATIVE STRAT UNIT ID:  The chronostratigraphic unit that is the upper equivalent age.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ROW_CHANGED_BY IS 'ROW CHANGED BY: Application login id of the user who last changed the row.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ROW_CHANGED_DATE IS 'ROW CHANGED DATE: System date of the last time the row was changed.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ROW_CREATED_BY IS 'ROW CREATED BY:  System user who created this row of data.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ROW_CREATED_DATE IS 'ROW CREATED DATE: Date that the row was created on.';

COMMENT ON COLUMN PPDM.TLM_STRAT_WELL_INTERP_AGE.ROW_QUALITY IS 'PPDM ROW QUALILTY:  A set of values indicating the quality of data in this row, usually with reference to the method or procedures used to load the data, although other types of quality reference are permitted.';



CREATE UNIQUE INDEX PPDM.TSTWIA_PK ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(UWI, STRAT_NAME_SET_ID, STRAT_UNIT_ID, INTERP_ID, AGE_SOURCE, 
AGE_ID)
LOGGING
TABLESPACE PPDM_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_R_SAM1_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(STRAT_AGE_METHOD)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_R_S_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(AGE_SOURCE)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX PPDM.TSTWIA_SRC_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(SOURCE)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_SRCD_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(SOURCE_DOCUMENT)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_STU_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(UPPER_REL_STRAT_NAME_SET, UPPER_REL_STRAT_UNIT_ID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_STU_IDX2 ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(AVERAGE_REL_STRAT_NAME_SET, AVERAGE_REL_STRAT_UNIT_ID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_STU_IDX3 ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(LOWER_REL_STRAT_NAME_SET, LOWER_REL_STRAT_UNIT_ID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PPDM.TSTWIA_STWS_IDX ON PPDM.TLM_STRAT_WELL_INTERP_AGE
(UWI, STRAT_NAME_SET_ID, STRAT_UNIT_ID, INTERP_ID)
LOGGING
TABLESPACE PPDM_INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM DATA_FINDER.TLM_STRAT_WELL_INTERP_AGE;

CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_STRAT_WELL_INTERP_AGE FOR PPDM.TLM_STRAT_WELL_INTERP_AGE;


DROP SYNONYM EDIOS_ADMIN.STRAT_WELL_INTERP_AGE;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_STRAT_WELL_INTERP_AGE FOR PPDM.TLM_STRAT_WELL_INTERP_AGE;



ALTER TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE ADD (
  CONSTRAINT TSTWIA_PK
  PRIMARY KEY
  (UWI, STRAT_NAME_SET_ID, STRAT_UNIT_ID, INTERP_ID, AGE_SOURCE, AGE_ID)
  USING INDEX PPDM.TSTWIA_PK
  ENABLE VALIDATE);

ALTER TABLE PPDM.TLM_STRAT_WELL_INTERP_AGE ADD (
  CONSTRAINT TSTWIA_R_SAM1_FK 
  FOREIGN KEY (STRAT_AGE_METHOD) 
  REFERENCES PPDM.R_STRAT_AGE_METHOD (STRAT_AGE_METHOD)
  ENABLE VALIDATE,
  CONSTRAINT TSTWIA_R_S_FK 
  FOREIGN KEY (AGE_SOURCE) 
  REFERENCES PPDM.R_SOURCE (SOURCE)
  ENABLE VALIDATE,
  CONSTRAINT TSTWIA_SRCD_FK 
  FOREIGN KEY (SOURCE_DOCUMENT) 
  REFERENCES PPDM.SOURCE_DOCUMENT (SOURCE_DOCUMENT)
  ENABLE VALIDATE,
  CONSTRAINT TSTWIA_STWS_FK 
  FOREIGN KEY (UWI, STRAT_NAME_SET_ID, STRAT_UNIT_ID, INTERP_ID) 
  REFERENCES PPDM.TLM_STRAT_WELL_SECTION (UWI,STRAT_NAME_SET_ID,STRAT_UNIT_ID,INTERP_ID)
  ENABLE VALIDATE);

GRANT INSERT, SELECT ON PPDM.TLM_STRAT_WELL_INTERP_AGE TO DATMANGEO_ADMIN;

GRANT SELECT ON PPDM.TLM_STRAT_WELL_INTERP_AGE TO EDIOS_ADMIN;

GRANT SELECT ON PPDM.TLM_STRAT_WELL_INTERP_AGE TO PPDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.TLM_STRAT_WELL_INTERP_AGE TO PPDM_RW;

--Insert from STRAT_WELL_INTERP_AGE table ( before deleting)

INsert into TLM_STRAT_WELL_INTERP_AGE
(UWI,STRAT_NAME_SET_ID,STRAT_UNIT_ID,INTERP_ID,AGE_SOURCE,AGE_ID,ACTIVE_IND,AVERAGE_AGE,AVERAGE_AGE_ERROR_MINUS,AVERAGE_AGE_ERROR_PLUS,AVERAGE_REL_STRAT_NAME_SET,AVERAGE_REL_STRAT_UNIT_ID,
EFFECTIVE_DATE,EXPIRY_DATE,LOWER_MAX_AGE,LOWER_MAX_AGE_ERROR_MINUS,LOWER_MAX_AGE_ERROR_PLUS,LOWER_MIN_AGE,LOWER_MIN_AGE_ERROR_MINUS,LOWER_MIN_AGE_ERROR_PLUS,
LOWER_REL_STRAT_NAME_SET,LOWER_REL_STRAT_UNIT_ID,POST_QUALIFIER,PPDM_GUID,PREFERRED_IND,PRE_QUALIFIER,REMARK,SOURCE_DOCUMENT,STRAT_AGE_METHOD,
UPPER_MAX_AGE,UPPER_MAX_AGE_ERROR_MINUS,UPPER_MAX_AGE_ERROR_PLUS,UPPER_MIN_AGE,UPPER_MIN_AGE_ERROR_MINUS,UPPER_MIN_AGE_ERROR_PLUS,UPPER_REL_STRAT_NAME_SET,
UPPER_REL_STRAT_UNIT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_QUALITY)

( Select UWI,STRAT_NAME_SET_ID,STRAT_UNIT_ID,INTERP_ID,AGE_SOURCE,AGE_ID,ACTIVE_IND,AVERAGE_AGE,AVERAGE_AGE_ERROR_MINUS,AVERAGE_AGE_ERROR_PLUS,AVERAGE_REL_STRAT_NAME_SET,AVERAGE_REL_STRAT_UNIT_ID,
EFFECTIVE_DATE,EXPIRY_DATE,LOWER_MAX_AGE,LOWER_MAX_AGE_ERROR_MINUS,LOWER_MAX_AGE_ERROR_PLUS,LOWER_MIN_AGE,LOWER_MIN_AGE_ERROR_MINUS,LOWER_MIN_AGE_ERROR_PLUS,
LOWER_REL_STRAT_NAME_SET,LOWER_REL_STRAT_UNIT_ID,POST_QUALIFIER,PPDM_GUID,PREFERRED_IND,PRE_QUALIFIER,REMARK,SOURCE_DOCUMENT,STRAT_AGE_METHOD,
UPPER_MAX_AGE,UPPER_MAX_AGE_ERROR_MINUS,UPPER_MAX_AGE_ERROR_PLUS,UPPER_MIN_AGE,UPPER_MIN_AGE_ERROR_MINUS,UPPER_MIN_AGE_ERROR_PLUS,UPPER_REL_STRAT_NAME_SET,
UPPER_REL_STRAT_UNIT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_QUALITY
 from STRAT_WELL_INTERP_AGE);