DROP DATABASE LINK C_TALISMAN_IHSDATA;

CREATE DATABASE LINK C_TALISMAN_IHSDATA
 CONNECT TO C_TALISMAN
 IDENTIFIED BY <PWD>
 USING 'IHSDATA';

--new db link to DM database, in order to get qa document number

DROP DATABASE LINK EDXP;

CREATE DATABASE LINK EDXP
 CONNECT TO DOCSADM
 IDENTIFIED BY <PWD>
 USING 'EDXP'
;

