DROP USER WIM_LOADER CASCADE;

CREATE USER WIM_LOADER
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE APP_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for WIM_LOADER 
  GRANT CONNECT TO WIM_LOADER;
  GRANT RESOURCE TO WIM_LOADER;
  GRANT R_APPBASE TO WIM_LOADER;
  GRANT WIM_RO TO WIM_LOADER;
  ALTER USER WIM_LOADER DEFAULT ROLE ALL;
  -- 2 System Privileges for WIM_LOADER 
  GRANT CREATE DATABASE LINK TO WIM_LOADER;
  GRANT UNLIMITED TABLESPACE TO WIM_LOADER;
  -- 2 Tablespace Quotas for WIM_LOADER 
  ALTER USER WIM_LOADER QUOTA UNLIMITED ON APP_DATA;
  ALTER USER WIM_LOADER QUOTA UNLIMITED ON APP_INDEXES;
  -- 30 Object Privileges for WIM_LOADER 
    GRANT INSERT, SELECT ON PPDM.BUSINESS_ASSOCIATE TO WIM_LOADER;
    GRANT SELECT ON PPDM.CS_COORDINATE_SYSTEM TO WIM_LOADER WITH GRANT OPTION;
    GRANT SELECT ON PPDM.R_WELL_STATUS TO WIM_LOADER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.WELL_ALIAS TO WIM_LOADER WITH GRANT OPTION;
    GRANT INSERT, SELECT ON PPDM.WELL_LICENSE TO WIM_LOADER;
    GRANT SELECT ON PPDM.WELL_NODE_M_B TO WIM_LOADER;
    GRANT SELECT, UPDATE ON PPDM.WELL_NODE_VERSION TO WIM_LOADER;
    GRANT INSERT, SELECT ON PPDM.WELL_STATUS TO WIM_LOADER;
    GRANT SELECT ON PPDM.WELL_VERSION TO WIM_LOADER;
  GRANT REFERENCES (SOURCE) ON PPDM.WELL_VERSION TO WIM_LOADER;
  GRANT REFERENCES (UWI) ON PPDM.WELL_VERSION TO WIM_LOADER;
    GRANT SELECT ON PPDM_ADMIN.TLM_PROCESS_LOG TO WIM_LOADER;
    GRANT EXECUTE ON PPDM_ADMIN.TLM_PROCESS_LOGGER TO WIM_LOADER;
    GRANT EXECUTE ON PPDM_ADMIN.TLM_UTIL TO WIM_LOADER WITH GRANT OPTION;
    GRANT SELECT ON VRAJPOOT.WIM_FIND_WELL_7CN TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_AUDIT TO WIM_LOADER;
    GRANT SELECT ON WIM.WIM_AUDIT_LOG TO WIM_LOADER;
    GRANT SELECT ON WIM.WIM_FIND_WELL TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_GATEWAY TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_ROLLUP TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_SEARCH TO WIM_LOADER;
    GRANT SELECT ON WIM.WIM_STG_ID_SEQ TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_REQUEST TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_WELL_LICENSE TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_WELL_NODE_M_B TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_WELL_NODE_VERSION TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_WELL_STATUS TO WIM_LOADER;
    GRANT INSERT, SELECT, UPDATE ON WIM.WIM_STG_WELL_VERSION TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_UTIL TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_VALIDATE TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_VALIDATE_CUST TO WIM_LOADER;
    GRANT EXECUTE ON WIM.WIM_WELL_ACTION TO WIM_LOADER;
