DROP VIEW PPDM.IHS_PID_PDEN;

/* Formatted on 4/2/2013 7:37:14 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_PID_PDEN
(
   ENTITY,
   PDEN_TYPE,
   SOURCE,
   ACTIVE_IND,
   COUNTRY,
   CURR_OPERATOR,
   ENTITY_NAME,
   STATUS_DATE,
   WELL_NUMBER,
   DISTRICT,
   PI_ENHANCED_REC,
   ASSIGNED_FIELD,
   GEOLOGIC_PROVINCE,
   NODE_ID,
   LOCATION_TABLE,
   ON_INJECTION_DATE,
   ON_PRODUCTION_DATE,
   SHORT_NAME,
   CRSTATUS,
   PLOT_NAME,
   PLOT_SYMBOL,
   FIELD_POOL_WILDCAT,
   PI_PRIMARY_PRODUCT,
   PROPRIETARY_IND,
   PROVINCE_STATE,
   PI_SITUATION_CD,
   TOP_DEPTH,
   BASE_DEPTH,
   PROJECT_NUMBER,
   ROW_CHANGED_BY,
   PI_REC_UPD_DATE,
   PI_USER_ID,
   PI_ROW_ADD_DATE
)
AS
   SELECT 
         WV.uwi AS "ENTITY",
          P.ENTITY_TYPE,
          '450PID' AS SOURCE,
          'Y' AS ACTIVE_IND,
         '7US', -- P.COUNTRY,
          P.CURR_OPERATOR,
          P.ENTITY_NAME,
          P.STATUS_DATE,
          P.WELL_NUMBER,
          P.DISTRICT,
          P.PI_ENHANCED_REC,
          P.ASSIGNED_FIELD,
          RGP.SHORT_NAME AS GEOLOGIC_PROVINCE,
          P.NODE_ID,
          P.LOCATION_TABLE,
          P.ON_INJECTION_DATE,
          P.ON_PRODUCTION_DATE,
          P.SHORT_NAME,
          P.CRSTATUS,
          P.PLOT_NAME,
          P.PLOT_SYMBOL,
          P.FIELD_POOL_WILDCAT,
          RPT.SHORT_NAME AS PI_PRIMARY_PRODUCT,
          P.PROPRIETARY_IND,
          RPS.SHORT_NAME AS PROVINCE_STATE,
          SUBSTR (PRS.LONG_NAME, 1, 20) AS PI_SITUATION_CD,
          PPW.TOP_DEPTH,
          PPW.BASE_DEPTH,
          W.PI_PROJECT_NUMBER,
          P.PI_USER_ID,
          P.PI_REC_UPD_DATE,
          P.PI_USER_ID,
          P.PI_ROW_ADD_DATE
     FROM PDEN@C_TALISMAN_PID_STG_IHSDATAQ P,
          PI_PDEN_WELL@C_TALISMAN_PID_STG_IHSDATAQ PPW,
          WELL_VERSION WV,
          R_GEOLOGIC_PROV@C_TALISMAN_PID_STG_IHSDATAQ RGP,
          R_PRODUCT_TYPE@C_TALISMAN_PID_STG_IHSDATAQ RPT,
          R_PROVINCE_STATE@C_TALISMAN_PID_STG_IHSDATAQ RPS,
          PI_R_SITUATION@C_TALISMAN_PID_STG_IHSDATAQ PRS,
          WELL@C_TALISMAN_PID_STG_IHSDATAQ W
    WHERE     P.ENTITY_TYPE = 'WELL'
          AND P.ENTITY = PPW.ENTITY
          AND PPW.WELL_IDENTIFIER = WV.WELL_NUM
          AND PPW.WELL_IDENTIFIER = W.UWI
          AND P.GEOLOGIC_PROVINCE = RGP.GEOLOGIC_PROVINCE
          AND P.PI_PRIMARY_PRODUCT = RPT.PRODUCT_TYPE
          AND P.PROVINCE_STATE = RPS.PROVINCE_STATE
          AND P.PI_SITUATION_CD = PRS.SITUATION_CODE
          AND WV.SOURCE ='450PID'
          and WV.ACTIVE_IND ='Y';


GRANT SELECT ON PPDM.IHS_PID_PDEN TO PPDM_RO;
