DROP VIEW PPDM.WELL_DIR_SRVY_STATION;

/* Formatted on 11/7/2012 11:29:47 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_DIR_SRVY_STATION
(
   UWI,
   SURVEY_ID,
   SOURCE,
   DEPTH_OBS_NO,
   ACTIVE_IND,
   AZIMUTH,
   AZIMUTH_OUOM,
   DOG_LEG_SEVERITY,
   EFFECTIVE_DATE,
   EW_DIRECTION,
   EXPIRY_DATE,
   INCLINATION,
   INCLINATION_OUOM,
   LATITUDE,
   LONGITUDE,
   NS_DIRECTION,
   POINT_TYPE,
   PPDM_GUID,
   REMARK,
   STATION_ID,
   STATION_MD,
   STATION_MD_OUOM,
   STATION_TVD,
   STATION_TVD_OUOM,
   VERTICAL_SECTION,
   VERTICAL_SECTION_OUOM,
   X_OFFSET,
   X_OFFSET_OUOM,
   Y_OFFSET,
   Y_OFFSET_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   GEOG_COORD_SYSTEM_ID,
   PROVINCE_STATE,
   LOCATION_QUALIFIER,
   IPL_UWI_LOCAL
)
AS
   SELECT "UWI",
          "SURVEY_ID",
          "SOURCE",
          "DEPTH_OBS_NO",
          "ACTIVE_IND",
          "AZIMUTH",
          "AZIMUTH_OUOM",
          "DOG_LEG_SEVERITY",
          "EFFECTIVE_DATE",
          "EW_DIRECTION",
          "EXPIRY_DATE",
          "INCLINATION",
          "INCLINATION_OUOM",
          "LATITUDE",
          "LONGITUDE",
          "NS_DIRECTION",
          "POINT_TYPE",
          "PPDM_GUID",
          "REMARK",
          "STATION_ID",
          "STATION_MD",
          "STATION_MD_OUOM",
          "STATION_TVD",
          "STATION_TVD_OUOM",
          "VERTICAL_SECTION",
          "VERTICAL_SECTION_OUOM",
          "X_OFFSET",
          "X_OFFSET_OUOM",
          "Y_OFFSET",
          "Y_OFFSET_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          "GEOG_COORD_SYSTEM_ID",
          "PROVINCE_STATE",
          "LOCATION_QUALIFIER",
          NULL
     FROM ppdm.tlm_well_dir_srvy_station
   UNION ALL
   SELECT "UWI",
          "SURVEY_ID",
          "SOURCE",
          "DEPTH_OBS_NO",
          "ACTIVE_IND",
          "AZIMUTH",
          "AZIMUTH_OUOM",
          "DOG_LEG_SEVERITY",
          "EFFECTIVE_DATE",
          "EW_DIRECTION",
          "EXPIRY_DATE",
          "INCLINATION",
          "INCLINATION_OUOM",
          "LATITUDE",
          "LONGITUDE",
          "NS_DIRECTION",
          "POINT_TYPE",
          "PPDM_GUID",
          "REMARK",
          "STATION_ID",
          "STATION_MD",
          "STATION_MD_OUOM",
          "STATION_TVD",
          "STATION_TVD_OUOM",
          "VERTICAL_SECTION",
          "VERTICAL_SECTION_OUOM",
          "X_OFFSET",
          "X_OFFSET_OUOM",
          "Y_OFFSET",
          "Y_OFFSET_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          "GEOG_COORD_SYSTEM_ID",
          "PROVINCE_STATE",
          "LOCATION_QUALIFIER",
          ipl_uwi_local
     FROM ihs_cdn_well_dir_srvy_stn
    UNION ALL
   SELECT "UWI",
          "SURVEY_ID",
          "SOURCE",
          "DEPTH_OBS_NO",
          "ACTIVE_IND",
          "AZIMUTH",
          "AZIMUTH_OUOM",
          "DOG_LEG_SEVERITY",
          "EFFECTIVE_DATE",
          "EW_DIRECTION",
          "EXPIRY_DATE",
          "INCLINATION",
          "INCLINATION_OUOM",
          "LATITUDE",
          "LONGITUDE",
          "NS_DIRECTION",
          "POINT_TYPE",
          "PPDM_GUID",
          "REMARK",
          "STATION_ID",
          "STATION_MD",
          "STATION_MD_OUOM",
          "STATION_TVD",
          "STATION_TVD_OUOM",
          "VERTICAL_SECTION",
          "VERTICAL_SECTION_OUOM",
          "X_OFFSET",
          "X_OFFSET_OUOM",
          "Y_OFFSET",
          "Y_OFFSET_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          "GEOG_COORD_SYSTEM_ID",
          "PROVINCE_STATE",
          "LOCATION_QUALIFIER",
          ' ' AS "ipl_uwi_local"
     FROM ihs_us_well_dir_srvy_station;    
 

DROP SYNONYM GEOWIZ.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOWIZ.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM GEOWIZ_SURVEY.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOWIZ_SURVEY.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM SDP.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM SDP.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM GEOWIZ_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOWIZ_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM GEOFRAME_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOFRAME_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM GEOWIZ_SURVEY_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOWIZ_SURVEY_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM SPATIAL_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM SPATIAL_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM SDP_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM SDP_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM PPDM.WDSS;

CREATE OR REPLACE SYNONYM PPDM.WDSS FOR PPDM.WELL_DIR_SRVY_STATION;


DROP SYNONYM DATA_FINDER.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION;


GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION TO DIR_SRVY_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.WELL_DIR_SRVY_STATION TO DIR_SRVY_RW;

GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION TO PPDM_RO;

GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION TO SPATIAL;
