DROP VIEW PPDM.WELL_DIR_SRVY_STATION_GF;

/* Formatted on 11/7/2012 11:29:47 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_DIR_SRVY_STATION_GF
(
   UWI,
   SURVEY_ID,
   SOURCE,
   DEPTH_OBS_NO,
   ACTIVE_IND,
   AZIMUTH,
   AZIMUTH_OUOM,
   DOG_LEG_SEVERITY,
   EFFECTIVE_DATE,
   EW_DIRECTION,
   EXPIRY_DATE,
   INCLINATION,
   INCLINATION_OUOM,
   LATITUDE,
   LONGITUDE,
   NS_DIRECTION,
   POINT_TYPE,
   PPDM_GUID,
   REMARK,
   STATION_ID,
   STATION_MD,
   STATION_MD_OUOM,
   STATION_TVD,
   STATION_TVD_OUOM,
   VERTICAL_SECTION,
   VERTICAL_SECTION_OUOM,
   X_OFFSET,
   X_OFFSET_OUOM,
   Y_OFFSET,
   Y_OFFSET_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   GEOG_COORD_SYSTEM_ID,
   PROVINCE_STATE,
   LOCATION_QUALIFIER,
   IPL_UWI_LOCAL
)
AS
   SELECT UWI,
   SURVEY_ID,
   SOURCE,
   DEPTH_OBS_NO,
   ACTIVE_IND,
   AZIMUTH,
   AZIMUTH_OUOM,
   DOG_LEG_SEVERITY,
   EFFECTIVE_DATE,
   EW_DIRECTION,
   EXPIRY_DATE,
   INCLINATION,
   INCLINATION_OUOM,
   LATITUDE,
   LONGITUDE,
   NS_DIRECTION,
   POINT_TYPE,
   PPDM_GUID,
   REMARK,
   STATION_ID,
   STATION_MD,
   STATION_MD_OUOM,
   STATION_TVD,
   STATION_TVD_OUOM,
   VERTICAL_SECTION,
   VERTICAL_SECTION_OUOM,
   X_OFFSET,
   X_OFFSET_OUOM,
   Y_OFFSET,
   Y_OFFSET_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
  -- GEOG_COORD_SYSTEM_ID,
        DECODE(GEOG_COORD_SYSTEM_ID,
              '4269',   'NAD83',
              '4267',   'NAD27',
              '4326',   'WGS84',
              '0000') as "GEOG_COORD_SYSTEM_ID",
   PROVINCE_STATE,
   LOCATION_QUALIFIER,
   IPL_UWI_LOCAL
     FROM ppdm.well_dir_srvy_station;    
 

DROP SYNONYM GEOFRAME_APPL.WELL_DIR_SRVY_STATION;

CREATE OR REPLACE SYNONYM GEOFRAME_APPL.WELL_DIR_SRVY_STATION FOR PPDM.WELL_DIR_SRVY_STATION_GF;


GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION_GF TO DIR_SRVY_RO;
GRANT DELETE, INSERT, SELECT, UPDATE ON PPDM.WELL_DIR_SRVY_STATION_GF TO DIR_SRVY_RW;
GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION_GF TO PPDM_RO;
GRANT SELECT ON PPDM.WELL_DIR_SRVY_STATION_GF TO SPATIAL;


select * from WELL_DIR_SRVY_STATION_GF;