

CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_ANAL_METHOD FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_DESCRIPTION FOR PPDM.TLM_WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM DATA_FINDER.TLM_WELL_CORE_REMARK FOR PPDM.TLM_WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_STRAT_UNIT FOR PPDM.WELL_CORE_STRAT_UNIT;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_SAMPLE_DESC FOR PPDM.WELL_CORE_SAMPLE_DESC;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_SAMPLE_ANAL FOR PPDM.WELL_CORE_SAMPLE_ANAL;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_REMARK FOR PPDM.WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_DESCRIPTION FOR PPDM.WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_ANALYSIS FOR PPDM.WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE_ANAL_METHOD FOR PPDM.WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_CORE FOR PPDM.WELL_CORE;


CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANAL_METHOD FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_DESCRIPTION FOR PPDM.TLM_WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.TLM_WELL_CORE_REMARK FOR PPDM.TLM_WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_STRAT_UNIT FOR PPDM.WELL_CORE_STRAT_UNIT;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_SAMPLE_DESC FOR PPDM.WELL_CORE_SAMPLE_DESC;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_SAMPLE_ANAL FOR PPDM.WELL_CORE_SAMPLE_ANAL;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_REMARK FOR PPDM.WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_DESCRIPTION FOR PPDM.WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_ANALYSIS FOR PPDM.WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE_ANAL_METHOD FOR PPDM.WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_CORE FOR PPDM.WELL_CORE;


CREATE OR REPLACE SYNONYM PPDM.WCRAM FOR PPDM.TLM_WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM PPDM.TWCRD FOR PPDM.TLM_WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM PPDM.WCRSU FOR PPDM.WELL_CORE_STRAT_UNIT;
CREATE OR REPLACE SYNONYM PPDM.WCRSD FOR PPDM.WELL_CORE_SAMPLE_DESC;
CREATE OR REPLACE SYNONYM PPDM.WCRSA FOR PPDM.WELL_CORE_SAMPLE_ANAL;
CREATE OR REPLACE SYNONYM PPDM.WCRM FOR PPDM.WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM PPDM.WCR FOR PPDM.WELL_CORE_REMARK;
CREATE OR REPLACE SYNONYM PPDM.WCRD FOR PPDM.WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM PPDM.WCD FOR PPDM.WELL_CORE_DESCRIPTION;
CREATE OR REPLACE SYNONYM PPDM.WCRA FOR PPDM.WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM PPDM.WCA FOR PPDM.WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM PPDM.WCRAM FOR PPDM.WELL_CORE_ANAL_METHOD;
CREATE OR REPLACE SYNONYM PPDM.WCAM FOR PPDM.WELL_CORE_ANAL_METHOD;



CREATE OR REPLACE SYNONYM PPDM_ADMIN.TLM_WELL_CORE_ANALYSIS FOR PPDM.TLM_WELL_CORE_ANALYSIS;
CREATE OR REPLACE SYNONYM PPDM_ADMIN.WELL_CORE_ANALYSIS FOR PPDM.WELL_CORE_ANALYSIS;





CREATE OR REPLACE SYNONYM WIM.WELL_CORE_ANALYSIS FOR PPDM.WELL_CORE_ANALYSIS;
