'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewWell

  '''<summary>
  '''btnDone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnDone As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As TalismanEnergy.WIM.iWIM.WellVersionDetail
    Get
      Return CType(MyBase.Master, TalismanEnergy.WIM.iWIM.WellVersionDetail)
    End Get
  End Property
End Class
