DROP VIEW PPDM.IHS_CDN_WELL_TEST_FLOW;

/* Formatted on 4/2/2013 11:36:08 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_CDN_WELL_TEST_FLOW
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   PERIOD_TYPE,
   PERIOD_OBS_NO,
   FLUID_TYPE,
   ACTIVE_IND,
   BASIC_SEDIMENT_IND,
   BLOW_DESC,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   GAS_RISER_DIAMETER,
   GAS_RISER_DIAMETER_OUOM,
   MAX_FLUID_RATE,
   MAX_FLUID_RATE_OUOM,
   MAX_FLUID_RATE_UOM,
   MAX_SURFACE_PRESSURE,
   MAX_SURFACE_PRESSURE_OUOM,
   MEASUREMENT_TECHNIQUE,
   PPDM_GUID,
   REMARK,
   SHAKEOUT_PERCENT,
   TTS_ELAPSED_TIME,
   TTS_ELAPSED_TIME_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT /*+ RULE */
         WV.UWI,
          WV.SOURCE,
          WTF.TEST_TYPE,
          WTF.RUN_NUM,
          WTF.TEST_NUM,
          WTF.PERIOD_TYPE,
          WTF.PERIOD_OBS_NO,
          WTF.FLUID_TYPE,
          WTF.ACTIVE_IND,
          WTF.BASIC_SEDIMENT_IND,
          WTF.BLOW_DESC,
          WTF.EFFECTIVE_DATE,
          WTF.EXPIRY_DATE,
          WTF.GAS_RISER_DIAMETER,
          WTF.GAS_RISER_DIAMETER_OUOM,
          WTF.MAX_FLUID_RATE,
          WTF.MAX_FLUID_RATE_OUOM,
          WTF.MAX_FLUID_RATE_UOM,
          WTF.MAX_SURFACE_PRESSURE,
          WTF.MAX_SURFACE_PRESSURE_OUOM,
          WTF.MEASUREMENT_TECHNIQUE,
          WTF.PPDM_GUID,
          WTF.REMARK,
          WTF.SHAKEOUT_PERCENT,
          WTF.TTS_ELAPSED_TIME,
          WTF.TTS_ELAPSED_TIME_OUOM,
          WTF.ROW_CHANGED_BY,
          WTF.ROW_CHANGED_DATE,
          WTF.ROW_CREATED_BY,
          WTF.ROW_CREATED_DATE,
          WTF.ROW_QUALITY,
          WTF.PROVINCE_STATE
     FROM WELL_TEST_FLOW@C_TALISMAN_IHSDATA WTF, Well_version WV
    WHERE     WV.IPL_UWI_LOCAL = WTF.UWI
          AND WV.SOURCE = '300IPL'
          AND WV.ACTIVE_IND = 'Y';


GRANT SELECT ON PPDM.IHS_CDN_WELL_TEST_FLOW TO PPDM_RO;
