DROP VIEW PPDM.IHS_US_WELL_TEST_EQUIPMENT;

/* Formatted on 4/2/2013 11:40:29 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_US_WELL_TEST_EQUIPMENT
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   EQUIPMENT_TYPE,
   EQUIP_OBS_NO,
   ACTIVE_IND,
   EFFECTIVE_DATE,
   EQUIP_LENGTH,
   EQUIP_LENGTH_OUOM,
   EQUIP_WEIGHT,
   EQUIP_WEIGHT_OUOM,
   EXPIRY_DATE,
   INSIDE_DIAMETER,
   INSIDE_DIAMETER_OUOM,
   OUTSIDE_DIAMETER,
   OUTSIDE_DIAMETER_OUOM,
   PPDM_GUID,
   REMARK,
   TOP_DEPTH,
   TOP_DEPTH_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   X_EQUIP_GRADE,
   PROVINCE_STATE
)
AS
   SELECT WV.UWI,
          WV.SOURCE,
          WTE.TEST_TYPE,
          WTE.RUN_NUM,
          WTE.TEST_NUM,
          WTE.EQUIPMENT_TYPE,
          WTE.EQUIP_OBS_NO,
          WTE.ACTIVE_IND,
          WTE.EFFECTIVE_DATE,
          WTE.EQUIP_LENGTH*.3048,
          'FT' AS "EQUIP_LENGTH_OUOM",
          WTE.EQUIP_WEIGHT,
          WTE.EQUIP_WEIGHT_OUOM,
          WTE.EXPIRY_DATE,
          WTE.INSIDE_DIAMETER,
          WTE.INSIDE_DIAMETER_OUOM,
          WTE.OUTSIDE_DIAMETER,
          WTE.OUTSIDE_DIAMETER_OUOM,
          WTE.PPDM_GUID,
          WTE.REMARK,
          WTE.TOP_DEPTH*.3048,
          'FT' AS "TOP_DEPTH_OUOM",
          WTE.ROW_CHANGED_BY,
          WTE.ROW_CHANGED_DATE,
          WTE.ROW_CREATED_BY,
          WTE.ROW_CREATED_DATE,
          WTE.ROW_QUALITY,
          WTE.X_EQUIP_GRADE,
          WTE.PROVINCE_STATE
     FROM well_test_equipment@C_TALISMAN_US_IHSDATAQ wte, well_version wv
    WHERE     wv.well_num = wte.uwi
          AND wv.SOURCE = '450PID'
          AND wv.active_ind = 'Y';


GRANT SELECT ON PPDM.IHS_US_WELL_TEST_EQUIPMENT TO PPDM_RO;
