DROP VIEW PPDM.IHS_CDN_WELL_TEST_MUD;

/* Formatted on 4/2/2013 11:36:09 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_CDN_WELL_TEST_MUD
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   MUD_TYPE,
   ACTIVE_IND,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   FILTRATE_RESISTIVITY,
   FILTRATE_RESISTIVITY_OUOM,
   FILTRATE_SALINITY,
   FILTRATE_SALINITY_OUOM,
   FILTRATE_SALINITY_UOM,
   FILTRATE_TEMPERATURE,
   FILTRATE_TEMPERATURE_OUOM,
   MUD_PH,
   MUD_RESISTIVITY,
   MUD_RESISTIVITY_OUOM,
   MUD_SALINITY,
   MUD_SALINITY_OUOM,
   MUD_SALINITY_UOM,
   MUD_SAMPLE_TYPE,
   MUD_TEMPERATURE,
   MUD_TEMPERATURE_OUOM,
   MUD_VISCOSITY,
   MUD_VISCOSITY_OUOM,
   MUD_WEIGHT,
   MUD_WEIGHT_OUOM,
   MUD_WEIGHT_UOM,
   PPDM_GUID,
   REMARK,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT /*+ RULE */
         wv.uwi,
          wv.SOURCE,
          wtmud.test_type,
          wtmud.run_num,
          wtmud.test_num,
          wtmud.mud_type,
          wtmud.active_ind,
          wtmud.effective_date,
          wtmud.expiry_date,
          wtmud.filtrate_resistivity,
          wtmud.filtrate_resistivity_ouom,
          wtmud.filtrate_salinity,
          wtmud.filtrate_salinity_ouom,
          wtmud.filtrate_salinity_uom,
          wtmud.filtrate_temperature,
          wtmud.filtrate_temperature_ouom,
          wtmud.mud_ph,
          wtmud.mud_resistivity,
          wtmud.mud_resistivity_ouom,
          wtmud.mud_salinity,
          wtmud.mud_salinity_ouom,
          wtmud.mud_salinity_uom,
          wtmud.mud_sample_type,
          wtmud.mud_temperature,
          wtmud.mud_temperature_ouom,
          wtmud.mud_viscosity,
          wtmud.mud_viscosity_ouom,
          wtmud.mud_weight,
          wtmud.mud_weight_ouom,
          wtmud.mud_weight_uom,
          wtmud.ppdm_guid,
          wtmud.remark,
          wtmud.row_changed_by,
          wtmud.row_changed_date,
          wtmud.row_created_by,
          wtmud.row_created_date,
          wtmud.row_quality,
          wtmud.province_state
     FROM well_test_mud@c_talisman_ihsdata wtmud, well_version wv
    WHERE     wv.ipl_uwi_local = wtmud.uwi
          AND wv.SOURCE = '300IPL'
          AND wv.active_ind = 'Y';


GRANT SELECT ON PPDM.IHS_CDN_WELL_TEST_MUD TO PPDM_RO;
