DROP VIEW PPDM.IHS_CDN_WELL_TEST_CUSHION;

/* Formatted on 4/2/2013 11:36:06 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_CDN_WELL_TEST_CUSHION
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   CUSHION_OBS_NO,
   ACTIVE_IND,
   CUSHION_GAS_PRESSURE,
   CUSHION_GAS_PRESSURE_OUOM,
   CUSHION_INHIBITOR_VOLUME,
   CUSHION_INHIBITOR_VOL_OUOM,
   CUSHION_LENGTH,
   CUSHION_LENGTH_OUOM,
   CUSHION_TYPE,
   CUSHION_VOLUME,
   CUSHION_VOLUME_OUOM,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   PPDM_GUID,
   REMARK,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT /*+ RULE */
         WV.UWI,
          WV.SOURCE,
          WTC.TEST_TYPE,
          WTC.RUN_NUM,
          WTC.TEST_NUM,
          WTC.CUSHION_OBS_NO,
          WTC.ACTIVE_IND,
          WTC.CUSHION_GAS_PRESSURE,
          WTC.CUSHION_GAS_PRESSURE_OUOM,
          WTC.CUSHION_INHIBITOR_VOLUME,
          WTC.CUSHION_INHIBITOR_VOL_OUOM,
          WTC.CUSHION_LENGTH,
          WTC.CUSHION_LENGTH_OUOM,
          WTC.CUSHION_TYPE,
          WTC.CUSHION_VOLUME,
          WTC.CUSHION_VOLUME_OUOM,
          WTC.EFFECTIVE_DATE,
          WTC.EXPIRY_DATE,
          WTC.PPDM_GUID,
          WTC.REMARK,
          WTC.ROW_CHANGED_BY,
          WTC.ROW_CHANGED_DATE,
          WTC.ROW_CREATED_BY,
          WTC.ROW_CREATED_DATE,
          WTC.ROW_QUALITY,
          WTC.PROVINCE_STATE
     FROM WELL_TEST_CUSHION@C_TALISMAN_IHSDATA WTC, Well_version WV
    WHERE     WV.IPL_UWI_LOCAL = WTC.UWI
          AND WV.SOURCE = '300IPL'
          AND WV.ACTIVE_IND = 'Y';


GRANT SELECT ON PPDM.IHS_CDN_WELL_TEST_CUSHION TO PPDM_RO;
