DROP VIEW PPDM.IHS_CDN_WELL_TEST_EQUIPMENT;

/* Formatted on 4/2/2013 11:36:07 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.IHS_CDN_WELL_TEST_EQUIPMENT
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   EQUIPMENT_TYPE,
   EQUIP_OBS_NO,
   ACTIVE_IND,
   EFFECTIVE_DATE,
   EQUIP_LENGTH,
   EQUIP_LENGTH_OUOM,
   EQUIP_WEIGHT,
   EQUIP_WEIGHT_OUOM,
   EXPIRY_DATE,
   INSIDE_DIAMETER,
   INSIDE_DIAMETER_OUOM,
   OUTSIDE_DIAMETER,
   OUTSIDE_DIAMETER_OUOM,
   PPDM_GUID,
   REMARK,
   TOP_DEPTH,
   TOP_DEPTH_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   X_EQUIP_GRADE,
   PROVINCE_STATE
)
AS
   SELECT /*+ RULE */
         WV.UWI,
          WV.SOURCE,
          WTE.TEST_TYPE,
          WTE.RUN_NUM,
          WTE.TEST_NUM,
          WTE.EQUIPMENT_TYPE,
          WTE.EQUIP_OBS_NO,
          WTE.ACTIVE_IND,
          WTE.EFFECTIVE_DATE,
          WTE.EQUIP_LENGTH,
          WTE.EQUIP_LENGTH_OUOM,
          WTE.EQUIP_WEIGHT,
          WTE.EQUIP_WEIGHT_OUOM,
          WTE.EXPIRY_DATE,
          WTE.INSIDE_DIAMETER,
          WTE.INSIDE_DIAMETER_OUOM,
          WTE.OUTSIDE_DIAMETER,
          WTE.OUTSIDE_DIAMETER_OUOM,
          WTE.PPDM_GUID,
          WTE.REMARK,
          WTE.TOP_DEPTH,
          WTE.TOP_DEPTH_OUOM,
          WTE.ROW_CHANGED_BY,
          WTE.ROW_CHANGED_DATE,
          WTE.ROW_CREATED_BY,
          WTE.ROW_CREATED_DATE,
          WTE.ROW_QUALITY,
          WTE.X_EQUIP_GRADE,
          WTE.PROVINCE_STATE
     FROM WELL_TEST_EQUIPMENT@C_TALISMAN_IHSDATA WTE, Well_version WV
    WHERE     WV.IPL_UWI_LOCAL = WTE.UWI
          AND WV.SOURCE = '300IPL'
          AND WV.ACTIVE_IND = 'Y';


GRANT SELECT ON PPDM.IHS_CDN_WELL_TEST_EQUIPMENT TO PPDM_RO;
