

CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_CONTAMINANT FOR PPDM.WELL_TEST_CONTAMINANT;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_CUSHION FOR PPDM.WELL_TEST_CUSHION;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_EQUIPMENT FOR PPDM.WELL_TEST_EQUIPMENT;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_FLOW FOR PPDM.WELL_TEST_FLOW;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_FLOW_MEAS FOR PPDM.WELL_TEST_FLOW_MEAS;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_MUD FOR PPDM.WELL_TEST_MUD;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_PERIOD FOR PPDM.WELL_TEST_PERIOD;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_PRESSURE FOR PPDM.WELL_TEST_PRESSURE;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_RECORDER FOR PPDM.WELL_TEST_RECORDER;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_RECOVERY FOR PPDM.WELL_TEST_RECOVERY;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_REMARK FOR PPDM.WELL_TEST_REMARK;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST FOR PPDM.WELL_TEST;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_ANALYSIS FOR PPDM.WELL_TEST_ANALYSIS;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_SLOPE FOR PPDM.WELL_TEST_SLOPE;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_BLOW_DESC FOR PPDM.WELL_TEST_BLOW_DESC;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_PRESS_MEAS FOR PPDM.WELL_TEST_PRESS_MEAS;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_QUALITY FOR PPDM.WELL_TEST_QUALITY;


CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST FOR PPDM.WELL_TEST;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_ANALYSIS FOR PPDM.WELL_TEST_ANALYSIS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_CONTAMINANT FOR PPDM.WELL_TEST_CONTAMINANT;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_CUSHION FOR PPDM.WELL_TEST_CUSHION;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_EQUIPMENT FOR PPDM.WELL_TEST_EQUIPMENT;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW FOR PPDM.WELL_TEST_FLOW;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW_MEAS FOR PPDM.WELL_TEST_FLOW_MEAS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_MUD FOR PPDM.WELL_TEST_MUD;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_PERIOD FOR PPDM.WELL_TEST_PERIOD;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_PRESSURE FOR PPDM.WELL_TEST_PRESSURE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_RECORDER FOR PPDM.WELL_TEST_RECORDER;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_RECOVERY FOR PPDM.WELL_TEST_RECOVERY;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_REMARK FOR PPDM.WELL_TEST_REMARK;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_SLOPE FOR PPDM.WELL_TEST_SLOPE;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_BLOW_DESC FOR PPDM.WELL_TEST_BLOW_DESC;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_PRESS_MEAS FOR PPDM.WELL_TEST_PRESS_MEAS;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_QUALITY FOR PPDM.WELL_TEST_QUALITY;



CREATE OR REPLACE SYNONYM PPDM.WT FOR PPDM.WELL_TEST;
CREATE OR REPLACE SYNONYM PPDM.WTA FOR PPDM.WELL_TEST_ANALYSIS;
CREATE OR REPLACE SYNONYM PPDM.WTC FOR PPDM.WELL_TEST_CONTAMINANT;
CREATE OR REPLACE SYNONYM PPDM.WTCU FOR PPDM.WELL_TEST_CUSHION;
CREATE OR REPLACE SYNONYM PPDM.WTE FOR PPDM.WELL_TEST_EQUIPMENT;
CREATE OR REPLACE SYNONYM PPDM.WTF FOR PPDM.WELL_TEST_FLOW;
CREATE OR REPLACE SYNONYM PPDM.WTFM FOR PPDM.WELL_TEST_FLOW_MEAS;
CREATE OR REPLACE SYNONYM PPDM.WTM FOR PPDM.WELL_TEST_MUD;
CREATE OR REPLACE SYNONYM PPDM.WTP FOR PPDM.WELL_TEST_PERIOD;
CREATE OR REPLACE SYNONYM PPDM.WTPSR FOR PPDM.WELL_TEST_PRESSURE;
CREATE OR REPLACE SYNONYM PPDM.WTR FOR PPDM.WELL_TEST_RECORDER;
CREATE OR REPLACE SYNONYM PPDM.WTRCV FOR PPDM.WELL_TEST_RECOVERY;
CREATE OR REPLACE SYNONYM PPDM.WTRM FOR PPDM.WELL_TEST_REMARK;
CREATE OR REPLACE SYNONYM PPDM.WTRM FOR PPDM.WELL_TEST_SLOPE;
CREATE OR REPLACE SYNONYM WTBD FOR WELL_TEST_BLOW_DESC;
CREATE OR REPLACE SYNONYM WTPM FOR WELL_TEST_PRESS_MEAS;
CREATE OR REPLACE SYNONYM WTQ FOR WELL_TEST_QUALITY;
