DROP VIEW PPDM.WELL_TEST_EQUIPMENT;

/* Formatted on 4/2/2013 11:41:01 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_TEST_EQUIPMENT
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   EQUIPMENT_TYPE,
   EQUIP_OBS_NO,
   ACTIVE_IND,
   EFFECTIVE_DATE,
   EQUIP_LENGTH,
   EQUIP_LENGTH_OUOM,
   EQUIP_WEIGHT,
   EQUIP_WEIGHT_OUOM,
   EXPIRY_DATE,
   INSIDE_DIAMETER,
   INSIDE_DIAMETER_OUOM,
   OUTSIDE_DIAMETER,
   OUTSIDE_DIAMETER_OUOM,
   PPDM_GUID,
   REMARK,
   TOP_DEPTH,
   TOP_DEPTH_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   X_EQUIP_GRADE,
   PROVINCE_STATE
)
AS
   SELECT "UWI",
          "SOURCE",
          "TEST_TYPE",
          "RUN_NUM",
          "TEST_NUM",
          "EQUIPMENT_TYPE",
          "EQUIP_OBS_NO",
          "ACTIVE_IND",
          "EFFECTIVE_DATE",
          "EQUIP_LENGTH",
          "EQUIP_LENGTH_OUOM",
          "EQUIP_WEIGHT",
          "EQUIP_WEIGHT_OUOM",
          "EXPIRY_DATE",
          "INSIDE_DIAMETER",
          "INSIDE_DIAMETER_OUOM",
          "OUTSIDE_DIAMETER",
          "OUTSIDE_DIAMETER_OUOM",
          "PPDM_GUID",
          "REMARK",
          "TOP_DEPTH",
          "TOP_DEPTH_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS EXTENSION
          NULL AS "X_EQUIP_GRADE",
          NULL AS "PROVINCE_STATE"
     FROM tlm_well_TEST_EQUIPMENT
   UNION ALL
   SELECT "UWI",
          "SOURCE",
          "TEST_TYPE",
          "RUN_NUM",
          "TEST_NUM",
          "EQUIPMENT_TYPE",
          "EQUIP_OBS_NO",
          "ACTIVE_IND",
          "EFFECTIVE_DATE",
          "EQUIP_LENGTH",
          "EQUIP_LENGTH_OUOM",
          "EQUIP_WEIGHT",
          "EQUIP_WEIGHT_OUOM",
          "EXPIRY_DATE",
          "INSIDE_DIAMETER",
          "INSIDE_DIAMETER_OUOM",
          "OUTSIDE_DIAMETER",
          "OUTSIDE_DIAMETER_OUOM",
          "PPDM_GUID",
          "REMARK",
          "TOP_DEPTH",
          "TOP_DEPTH_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS EXTENSION
          "X_EQUIP_GRADE",
          "PROVINCE_STATE"
     FROM IHS_CDN_WELL_TEST_EQUIPMENT
   UNION ALL
   SELECT "UWI",
          "SOURCE",
          "TEST_TYPE",
          "RUN_NUM",
          "TEST_NUM",
          "EQUIPMENT_TYPE",
          "EQUIP_OBS_NO",
          "ACTIVE_IND",
          "EFFECTIVE_DATE",
          "EQUIP_LENGTH",
          "EQUIP_LENGTH_OUOM",
          "EQUIP_WEIGHT",
          "EQUIP_WEIGHT_OUOM",
          "EXPIRY_DATE",
          "INSIDE_DIAMETER",
          "INSIDE_DIAMETER_OUOM",
          "OUTSIDE_DIAMETER",
          "OUTSIDE_DIAMETER_OUOM",
          "PPDM_GUID",
          "REMARK",
          "TOP_DEPTH",
          "TOP_DEPTH_OUOM",
          "ROW_CHANGED_BY",
          "ROW_CHANGED_DATE",
          "ROW_CREATED_BY",
          "ROW_CREATED_DATE",
          "ROW_QUALITY",
          -- IHS EXTENSION
          "X_EQUIP_GRADE",
          "PROVINCE_STATE"
     FROM IHS_US_WELL_TEST_EQUIPMENT;


DROP SYNONYM DATA_FINDER.WELL_TEST_EQUIPMENT;

CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_EQUIPMENT FOR PPDM.WELL_TEST_EQUIPMENT;


DROP SYNONYM EDIOS_ADMIN.WELL_TEST_EQUIPMENT;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_EQUIPMENT FOR PPDM.WELL_TEST_EQUIPMENT;


DROP SYNONYM PPDM.WTE;

CREATE OR REPLACE SYNONYM PPDM.WTE FOR PPDM.WELL_TEST_EQUIPMENT;



GRANT SELECT ON PPDM.WELL_TEST_EQUIPMENT TO PPDM_RO;
