DROP VIEW PPDM.WELL_TEST_FLOW;

/* Formatted on 4/2/2013 11:41:02 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_TEST_FLOW
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   PERIOD_TYPE,
   PERIOD_OBS_NO,
   FLUID_TYPE,
   ACTIVE_IND,
   BASIC_SEDIMENT_IND,
   BLOW_DESC,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   GAS_RISER_DIAMETER,
   GAS_RISER_DIAMETER_OUOM,
   MAX_FLUID_RATE,
   MAX_FLUID_RATE_OUOM,
   MAX_FLUID_RATE_UOM,
   MAX_SURFACE_PRESSURE,
   MAX_SURFACE_PRESSURE_OUOM,
   MEASUREMENT_TECHNIQUE,
   PPDM_GUID,
   REMARK,
   SHAKEOUT_PERCENT,
   TTS_ELAPSED_TIME,
   TTS_ELAPSED_TIME_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          PERIOD_TYPE,
          PERIOD_OBS_NO,
          FLUID_TYPE,
          ACTIVE_IND,
          BASIC_SEDIMENT_IND,
          BLOW_DESC,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          GAS_RISER_DIAMETER,
          GAS_RISER_DIAMETER_OUOM,
          MAX_FLUID_RATE,
          MAX_FLUID_RATE_OUOM,
          MAX_FLUID_RATE_UOM,
          MAX_SURFACE_PRESSURE,
          MAX_SURFACE_PRESSURE_OUOM,
          MEASUREMENT_TECHNIQUE,
          PPDM_GUID,
          REMARK,
          SHAKEOUT_PERCENT,
          TTS_ELAPSED_TIME,
          TTS_ELAPSED_TIME_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS EXTENSION
          NULL AS PROVINCE_STATE
     FROM tlm_well_TEST_FLOW
   UNION ALL
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          PERIOD_TYPE,
          PERIOD_OBS_NO,
          FLUID_TYPE,
          ACTIVE_IND,
          BASIC_SEDIMENT_IND,
          BLOW_DESC,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          GAS_RISER_DIAMETER,
          GAS_RISER_DIAMETER_OUOM,
          MAX_FLUID_RATE,
          MAX_FLUID_RATE_OUOM,
          MAX_FLUID_RATE_UOM,
          MAX_SURFACE_PRESSURE,
          MAX_SURFACE_PRESSURE_OUOM,
          MEASUREMENT_TECHNIQUE,
          PPDM_GUID,
          REMARK,
          SHAKEOUT_PERCENT,
          TTS_ELAPSED_TIME,
          TTS_ELAPSED_TIME_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS EXTENSION
          PROVINCE_STATE
     FROM IHS_CDN_WELL_TEST_FLOW
   UNION ALL
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          PERIOD_TYPE,
          PERIOD_OBS_NO,
          FLUID_TYPE,
          ACTIVE_IND,
          BASIC_SEDIMENT_IND,
          BLOW_DESC,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          GAS_RISER_DIAMETER,
          GAS_RISER_DIAMETER_OUOM,
          MAX_FLUID_RATE,
          MAX_FLUID_RATE_OUOM,
          MAX_FLUID_RATE_UOM,
          MAX_SURFACE_PRESSURE,
          MAX_SURFACE_PRESSURE_OUOM,
          MEASUREMENT_TECHNIQUE,
          PPDM_GUID,
          REMARK,
          SHAKEOUT_PERCENT,
          TTS_ELAPSED_TIME,
          TTS_ELAPSED_TIME_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS EXTENSION
          PROVINCE_STATE
     FROM IHS_US_WELL_TEST_FLOW;


DROP SYNONYM DATA_FINDER.WELL_TEST_FLOW;
CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_FLOW FOR PPDM.WELL_TEST_FLOW;


DROP SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW;
CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW FOR PPDM.WELL_TEST_FLOW;


DROP SYNONYM PPDM.WTF;
CREATE OR REPLACE SYNONYM PPDM.WTF FOR PPDM.WELL_TEST_FLOW;


GRANT SELECT ON PPDM.WELL_TEST_FLOW TO PPDM_RO;
