DROP VIEW PPDM.WELL_TEST_CONTAMINANT;

/* Formatted on 4/2/2013 11:40:59 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_TEST_CONTAMINANT
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   RECOVERY_OBS_NO,
   CONTAMINANT_SEQ_NO,
   ACTIVE_IND,
   CONTAMINANT_TYPE,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   PPDM_GUID,
   REMARK,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT TWTC."UWI",
          TWTC."SOURCE",
          TWTC."TEST_TYPE",
          TWTC."RUN_NUM",
          TWTC."TEST_NUM",
          TWTC."RECOVERY_OBS_NO",
          TWTC."CONTAMINANT_SEQ_NO",
          TWTC."ACTIVE_IND",
          TWTC."CONTAMINANT_TYPE",
          TWTC."EFFECTIVE_DATE",
          TWTC."EXPIRY_DATE",
          TWTC."PPDM_GUID",
          TWTC."REMARK",
          TWTC."ROW_CHANGED_BY",
          TWTC."ROW_CHANGED_DATE",
          TWTC."ROW_CREATED_BY",
          TWTC."ROW_CREATED_DATE",
          TWTC."ROW_QUALITY",
          -- IHS extension
          NULL AS "PROVINCE_STATE"
     FROM tlm_well_TEST_CONTAMINANT TWTC
   UNION ALL
   SELECT ICWTC."UWI",
          ICWTC."SOURCE",
          ICWTC."TEST_TYPE",
          ICWTC."RUN_NUM",
          ICWTC."TEST_NUM",
          ICWTC."RECOVERY_OBS_NO",
          ICWTC."CONTAMINANT_SEQ_NO",
          ICWTC."ACTIVE_IND",
          ICWTC."CONTAMINANT_TYPE",
          ICWTC."EFFECTIVE_DATE",
          ICWTC."EXPIRY_DATE",
          ICWTC."PPDM_GUID",
          ICWTC."REMARK",
          ICWTC."ROW_CHANGED_BY",
          ICWTC."ROW_CHANGED_DATE",
          ICWTC."ROW_CREATED_BY",
          ICWTC."ROW_CREATED_DATE",
          ICWTC."ROW_QUALITY",
          -- IHS extension
          ICWTC."PROVINCE_STATE"
     FROM IHS_CDN_WELL_TEST_CONTAMINANT ICWTC
   UNION ALL
   SELECT IUWTC."UWI",
          IUWTC."SOURCE",
          IUWTC."TEST_TYPE",
          IUWTC."RUN_NUM",
          IUWTC."TEST_NUM",
          IUWTC."RECOVERY_OBS_NO",
          IUWTC."CONTAMINANT_SEQ_NO",
          IUWTC."ACTIVE_IND",
          IUWTC."CONTAMINANT_TYPE",
          IUWTC."EFFECTIVE_DATE",
          IUWTC."EXPIRY_DATE",
          IUWTC."PPDM_GUID",
          IUWTC."REMARK",
          IUWTC."ROW_CHANGED_BY",
          IUWTC."ROW_CHANGED_DATE",
          IUWTC."ROW_CREATED_BY",
          IUWTC."ROW_CREATED_DATE",
          IUWTC."ROW_QUALITY",
          -- IHS extension
          IUWTC."PROVINCE_STATE"
     FROM IHS_US_WELL_TEST_CONTAMINANT IUWTC;


DROP SYNONYM DATA_FINDER.WELL_TEST_CONTAMINANT;

CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_CONTAMINANT FOR PPDM.WELL_TEST_CONTAMINANT;


DROP SYNONYM EDIOS_ADMIN.WELL_TEST_CONTAMINANT;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_CONTAMINANT FOR PPDM.WELL_TEST_CONTAMINANT;


DROP SYNONYM PPDM.WTC;

CREATE OR REPLACE SYNONYM PPDM.WTC FOR PPDM.WELL_TEST_CONTAMINANT;


GRANT SELECT ON PPDM.WELL_TEST_CONTAMINANT TO PPDM_RO;
