DROP VIEW PPDM.WELL_TEST_FLOW_MEAS;

/* Formatted on 4/2/2013 11:41:02 AM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE FORCE VIEW PPDM.WELL_TEST_FLOW_MEAS
(
   UWI,
   SOURCE,
   TEST_TYPE,
   RUN_NUM,
   TEST_NUM,
   MEASUREMENT_OBS_NO,
   ACTIVE_IND,
   EFFECTIVE_DATE,
   EXPIRY_DATE,
   FLOW_DURATION,
   FLOW_DURATION_OUOM,
   FLUID_TYPE,
   MEASUREMENT_PRESSURE,
   MEASUREMENT_PRESSURE_OUOM,
   MEASUREMENT_TIME,
   MEASUREMENT_TIME_OUOM,
   MEASUREMENT_VOLUME,
   MEASUREMENT_VOLUME_OUOM,
   MEASUREMENT_VOLUME_UOM,
   PERIOD_OBS_NO,
   PERIOD_TYPE,
   PPDM_GUID,
   REMARK,
   SURFACE_CHOKE_DIAMETER,
   SURFACE_CHOKE_DIAMETER_OUOM,
   ROW_CHANGED_BY,
   ROW_CHANGED_DATE,
   ROW_CREATED_BY,
   ROW_CREATED_DATE,
   ROW_QUALITY,
   PROVINCE_STATE
)
AS
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          MEASUREMENT_OBS_NO,
          ACTIVE_IND,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          FLOW_DURATION,
          FLOW_DURATION_OUOM,
          FLUID_TYPE,
          MEASUREMENT_PRESSURE,
          MEASUREMENT_PRESSURE_OUOM,
          MEASUREMENT_TIME,
          MEASUREMENT_TIME_OUOM,
          MEASUREMENT_VOLUME,
          MEASUREMENT_VOLUME_OUOM,
          MEASUREMENT_VOLUME_UOM,
          PERIOD_OBS_NO,
          PERIOD_TYPE,
          PPDM_GUID,
          REMARK,
          SURFACE_CHOKE_DIAMETER,
          SURFACE_CHOKE_DIAMETER_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS extensions
          NULL AS PROVINCE_STATE
     FROM tlm_well_TEST_FLOW_MEAS
   UNION ALL
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          MEASUREMENT_OBS_NO,
          ACTIVE_IND,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          FLOW_DURATION,
          FLOW_DURATION_OUOM,
          FLUID_TYPE,
          MEASUREMENT_PRESSURE,
          MEASUREMENT_PRESSURE_OUOM,
          MEASUREMENT_TIME,
          MEASUREMENT_TIME_OUOM,
          MEASUREMENT_VOLUME,
          MEASUREMENT_VOLUME_OUOM,
          MEASUREMENT_VOLUME_UOM,
          PERIOD_OBS_NO,
          PERIOD_TYPE,
          PPDM_GUID,
          REMARK,
          SURFACE_CHOKE_DIAMETER,
          SURFACE_CHOKE_DIAMETER_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS extensions
          PROVINCE_STATE
     FROM IHS_CDN_WELL_TEST_FLOW_MEAS
   UNION ALL
   SELECT UWI,
          SOURCE,
          TEST_TYPE,
          RUN_NUM,
          TEST_NUM,
          MEASUREMENT_OBS_NO,
          ACTIVE_IND,
          EFFECTIVE_DATE,
          EXPIRY_DATE,
          FLOW_DURATION,
          FLOW_DURATION_OUOM,
          FLUID_TYPE,
          MEASUREMENT_PRESSURE,
          MEASUREMENT_PRESSURE_OUOM,
          MEASUREMENT_TIME,
          MEASUREMENT_TIME_OUOM,
          MEASUREMENT_VOLUME,
          MEASUREMENT_VOLUME_OUOM,
          MEASUREMENT_VOLUME_UOM,
          PERIOD_OBS_NO,
          PERIOD_TYPE,
          PPDM_GUID,
          REMARK,
          SURFACE_CHOKE_DIAMETER,
          SURFACE_CHOKE_DIAMETER_OUOM,
          ROW_CHANGED_BY,
          ROW_CHANGED_DATE,
          ROW_CREATED_BY,
          ROW_CREATED_DATE,
          ROW_QUALITY,
          -- IHS extensions
          PROVINCE_STATE
     FROM IHS_US_WELL_TEST_FLOW_MEAS;


DROP SYNONYM DATA_FINDER.WELL_TEST_FLOW_MEAS;

CREATE OR REPLACE SYNONYM DATA_FINDER.WELL_TEST_FLOW_MEAS FOR PPDM.WELL_TEST_FLOW_MEAS;


DROP SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW_MEAS;

CREATE OR REPLACE SYNONYM EDIOS_ADMIN.WELL_TEST_FLOW_MEAS FOR PPDM.WELL_TEST_FLOW_MEAS;


DROP SYNONYM PPDM.WTFM;

CREATE OR REPLACE SYNONYM PPDM.WTFM FOR PPDM.WELL_TEST_FLOW_MEAS;



GRANT SELECT ON PPDM.WELL_TEST_FLOW_MEAS TO PPDM_RO;
