
--RUN AS PPDM_ADMIN USER
DROP USER FME_APPL CASCADE;

CREATE USER FME_APPL
  IDENTIFIED BY "winter3"
  DEFAULT TABLESPACE APP_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  -- ROLES 
  GRANT R_APPLICATION TO FME_APPL;
  GRANT PPDM_RO TO FME_APPL;
  
  ALTER USER FME_APPL DEFAULT ROLE ALL;  
  
  -- System Privileges for SPATIAL 
  --GRANT CREATE SESSION TO FME_APPL;  --included in role R_APPLICATION

  -- Tablespace Quotas
  ALTER USER FME_APPL QUOTA UNLIMITED ON APP_DATA;
  ALTER USER FME_APPL QUOTA UNLIMITED ON APP_INDEXES;

  -- Object Privileges 
  