drop table TEMP100_ALIAS_UPDATE;

create table TEMP100_ALIAS_UPDATE as select uwi
from well_version where source = '100TLM' and uwi not in
(select well_alias from well_alias where source like '100TLM' and well_alias like uwi);

Alter table TEMP100_ALIAS_UPDATE ADD  WELL_ALIAS VARCHAR2(66);
Alter table TEMP100_ALIAS_UPDATE ADD  WELL_ALIAS_ID  VARCHAR2(66);
Alter table TEMP100_ALIAS_UPDATE ADD  ALIAS_TYPE VARCHAR2(20);
Alter table TEMP100_ALIAS_UPDATE ADD  SOURCE VARCHAR2(20);
Alter table TEMP100_ALIAS_UPDATE ADD  ROW_CREATED_BY VARCHAR2(30);
Alter table TEMP100_ALIAS_UPDATE ADD  ROW_CREATED_DATE DATE;
Update TEMP100_ALIAS_UPDATE set WELL_ALIAS = UWI;
Update TEMP100_ALIAS_UPDATE set ALIAS_TYPE = 'UWI';
Update TEMP100_ALIAS_UPDATE set SOURCE = '100TLM';
Update TEMP100_ALIAS_UPDATE set ROW_CREATED_BY = 'RMELIN';
Update TEMP100_ALIAS_UPDATE set ROW_CREATED_DATE = sysdate;
Update TEMP100_ALIAS_UPDATE set WELL_ALIAS_ID = 'TLM';

select count (*) from TEMP100_ALIAS_UPDATE;
desc TEMP100_ALIAS_UPDATE;

INSERT INTO WELL_ALIAS
(UWI,WELL_ALIAS,WELL_ALIAS_ID,ALIAS_TYPE,SOURCE,ROW_CREATED_BY,ROW_CREATED_DATE)
SELECT UWI,WELL_ALIAS,WELL_ALIAS_ID,ALIAS_TYPE,SOURCE,ROW_CREATED_BY,ROW_CREATED_DATE
FROM TEMP100_ALIAS_UPDATE;

commit;



